import React, { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'bn' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string, params?: Record<string, string>) => string;
  formatNumber: (n: number | string) => string;
  formatCurrency: (n: number | string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  bn: {
    // Header & General
    'nav.home': 'হোম',
    'nav.about': 'আমাদের সম্পর্কে',
    'nav.terms': 'শর্তাবলী',
    'nav.refund': 'রিফান্ড পলিসি',
    'nav.login': 'লগইন',
    'nav.admin': 'এডমিন',
    'nav.owner': 'বাস মালিক',
    'nav.counter': 'কাউন্টার',
    'nav.logout': 'লগআউট',
    'footer.rights': 'সর্বস্বত্ব সংরক্ষিত।',
    'btn.back': 'ফিরে যান',
    'btn.close': 'বন্ধ করুন',
    'btn.home': 'হোম পেইজে ফিরে যান',
    'brand.name': 'টিকিট লাগবে',
    'brand.subtitle': 'Premium Bus Service',

    // Chat
    'chat.welcome': 'আসসালামু আলাইকুম! টিকিট লাগবে সাপোর্ট সেন্টারে আপনাকে স্বাগতম। আমি আপনাকে কিভাবে সাহায্য করতে পারি?',
    'chat.error': 'দুঃখিত, চ্যাট সার্ভিসটি এই মুহূর্তে কাজ করছে না। API Key চেক করুন।',
    'chat.header.title': 'কাস্টমার সাপোর্ট',
    'chat.header.subtitle': 'টিকিট লাগবে এআই',
    'chat.input.placeholder': 'আপনার প্রশ্ন লিখুন...',
    'chat.quick.timings': 'বাসের সময়সূচী',
    'chat.quick.routes': 'রুটসমূহ',
    'chat.quick.fare': 'ভাড়া',
    'chat.quick.timings.query': 'বাসের সময়সূচী জানতে চাই',
    'chat.quick.routes.query': 'আপনাদের রুটগুলো কি কি?',
    'chat.quick.fare.query': 'টিকিটের ভাড়া কত?',

    // Footer
    'footer.contact': 'যোগাযোগ',
    'footer.links': 'লিঙ্ক',
    'footer.about_desc': 'টিকিট লাগবে বাংলাদেশের একটি প্রিমিয়াম বাস সার্ভিস। আমরা যাত্রীদের সর্বোচ্চ আরাম এবং নিরাপত্তা নিশ্চিত করতে প্রতিশ্রুতিবদ্ধ।',
    'footer.address': 'ঢাকা, বাংলাদেশ',
    'footer.home': 'হোম',
    'footer.booking': 'বুকিং',
    'footer.support': 'সাপোর্ট',
    'nav.offers': 'অফার',
    'nav.profile': 'প্রোফাইল',
    'nav.passenger_dashboard': 'যাত্রী ড্যাশবোর্ড',
    'nav.profile_profile': 'প্রোফাইল',
    'passenger.dashboard.title': 'যাত্রী ড্যাশবোর্ড',
    'passenger.dashboard.welcome': 'স্বাগতম, {{name}}!',
    'passenger.dashboard.subtitle': 'আপনার ভ্রমণ এবং বুকিং এখান থেকে পরিচালনা করুন।',
    'passenger.dashboard.upcoming_trips': 'আসন্ন ভ্রমণ',
    'passenger.dashboard.past_trips': 'অতীত ভ্রমণ',
    'passenger.dashboard.loyalty_points': 'লয়্যালটি পয়েন্ট',
    'passenger.dashboard.book_now': 'এখনই বুক করুন',
    'passenger.dashboard.no_trips': 'আপনার কোনো আসন্ন ভ্রমণ নেই।',
    'passenger.dashboard.quick_actions': 'কুইক অ্যাকশন',
    'passenger.dashboard.track_bus': 'বাস ট্র্যাক করুন',
    'passenger.dashboard.cancel_ticket': 'টিকিট বাতিল',
    'passenger.dashboard.support': 'সাপোর্ট',
    'passenger.dashboard.profile_summary': 'প্রোফাইল সারাংশ',
    'passenger.dashboard.member_id': 'মেম্বার আইডি',
    'passenger.dashboard.total_spent': 'মোট খরচ',
    'passenger.dashboard.trips_completed': 'ভ্রমণ সম্পন্ন',
    'passenger.dashboard.transactions': 'লেনদেন ইতিহাস',
    'passenger.dashboard.change_password': 'পাসওয়ার্ড পরিবর্তন',
    'passenger.dashboard.old_password': 'পুরানো পাসওয়ার্ড',
    'passenger.dashboard.new_password': 'নতুন পাসওয়ার্ড',
    'passenger.dashboard.confirm_password': 'পাসওয়ার্ড নিশ্চিত করুন',
    'passenger.dashboard.password_mismatch': 'পাসওয়ার্ড মেলেনি',
    'passenger.dashboard.password_success': 'পাসওয়ার্ড সফলভাবে পরিবর্তন হয়েছে',
    'passenger.dashboard.password_error': 'পাসওয়ার্ড পরিবর্তন ব্যর্থ হয়েছে',
    'passenger.dashboard.track_bus_title': 'বাস ট্র্যাকিং',
    'passenger.dashboard.bus_status': 'বাসের অবস্থা',
    'passenger.dashboard.current_speed': 'বর্তমান গতি',
    'passenger.dashboard.next_stop': 'পরবর্তী স্টপেজ',
    'passenger.dashboard.last_updated': 'সর্বশেষ আপডেট',
    'passenger.dashboard.transaction_id': 'লেনদেন আইডি',
    'passenger.dashboard.transaction_type': 'ধরণ',
    'passenger.dashboard.transaction_method': 'পদ্ধতি',
    'passenger.dashboard.transaction_amount': 'পরিমাণ',
    'passenger.dashboard.transaction_date': 'তারিখ',
    'passenger.dashboard.no_transactions': 'কোন লেনদেন পাওয়া যায়নি',
    'passenger.dashboard.refund_ticket': 'টিকিট রিফান্ড',
    'passenger.dashboard.refund_confirm': 'আপনি কি নিশ্চিত যে আপনি এই টিকিটের রিফান্ড অনুরোধ করতে চান?',
    'passenger.dashboard.refund_success': 'রিফান্ড অনুরোধ সফলভাবে পাঠানো হয়েছে।',
    'passenger.dashboard.refund_failed': 'রিফান্ড অনুরোধ পাঠানো সম্ভব হয়নি।',
    'passenger.dashboard.refund_status': 'রিফান্ড অনুরোধ করা হয়েছে',
    'booking.hero.title': 'আপনার নিরাপদ ভ্রমণের বিশ্বস্ত সঙ্গী',
    'booking.hero.subtitle': 'দেশের সেরা বাস সার্ভিসগুলো থেকে আপনার পছন্দের সিটটি বুক করুন মাত্র কয়েক ক্লিকে।',
    'booking.search.from_placeholder': 'প্রস্থান শহর',
    'booking.search.to_placeholder': 'গন্তব্য শহর',
    'booking.results.count': 'উপলব্ধ বাসসমূহ',
    'booking.results.change': 'সার্চ পরিবর্তন করুন',
    'booking.results.per_person': 'জনপ্রতি',
    'booking.results.select_seats': 'আসন নির্বাচন করুন',
    'booking.seats.title': 'আপনার আসন নির্বাচন করুন',
    'booking.seats.available': 'উপলব্ধ',
    'booking.seats.booked': 'বুকড',
    'booking.summary.title': 'বুকিং সারাংশ',
    'booking.summary.bus': 'বাস',
    'booking.summary.seats': 'আসন',
    'booking.summary.none': 'কোনটিই নয়',
    'booking.summary.total': 'মোট ভাড়া',
    'booking.summary.proceed': 'চেকআউটে যান',
    'booking.passenger.details': 'যাত্রীর বিবরণ',
    'booking.passenger.fullname': 'পুরো নাম',
    'booking.passenger.name_placeholder': 'আপনার নাম লিখুন',
    'booking.passenger.phone_placeholder': '০১XXX-XXXXXX',
    'booking.passenger.email': 'ইমেইল এড্রেস',
    'booking.passenger.identity': 'এন আই ডি/জন্ম সনদ/পাসপোর্ট',
    'booking.passenger.district': 'জেলা',
    'booking.passenger.thana': 'থানা',
    'booking.passenger.postOffice': 'পোষ্ট অফিস ও কোড',
    'booking.passenger.village': 'গ্রাম',
    'booking.payment.method': 'পেমেন্ট পদ্ধতি',
    'booking.payment.secured': 'SSLCommerz দ্বারা সুরক্ষিত',
    'booking.payment.confirm_pay': 'নিশ্চিত করুন এবং পেমেন্ট করুন',
    'booking.confirmation.subtitle': 'টিকিট লাগবে বেছে নেওয়ার জন্য ধন্যবাদ। আপনার টিকিট প্রস্তুত।',
    'booking.confirmation.no': 'কনফার্মেশন নম্বর',
    'booking.confirmation.passenger': 'যাত্রী',
    'booking.confirmation.phone': 'ফোন',
    'booking.confirmation.bus': 'বাস সার্ভিস',
    'booking.confirmation.seats': 'আসন',
    'booking.confirmation.departure': 'প্রস্থান',
    'booking.confirmation.total': 'মোট পরিশোধিত',
    'booking.confirmation.issued_by': 'ইস্যুকারী',
    'booking.confirmation.date_issued': 'ইস্যুর তারিখ',
    'booking.confirmation.print': 'টিকিট প্রিন্ট করুন',
    'booking.confirmation.back': 'হোমে ফিরে যান',
    'my_bookings.title': 'আমার বুকিং',
    'my_bookings.subtitle': 'আপনার অতীত এবং আসন্ন ভ্রমণগুলো পরিচালনা করুন',
    'my_bookings.new_trip': 'নতুন ট্রিপ বুক করুন',
    'my_bookings.upcoming': 'আসন্ন',
    'my_bookings.completed': 'সম্পন্ন',
    'my_bookings.cancelled': 'বাতিল',
    'my_bookings.view_details': 'বিস্তারিত দেখুন',
    'my_bookings.cancel_booking': 'বুকিং বাতিল করুন',
    'my_bookings.details_title': 'বুকিং বিস্তারিত',
    'my_bookings.close': 'বন্ধ করুন',
    'footer.about_title': 'আমাদের সম্পর্কে',
    'footer.about_desc_portal': 'টিকিট লাগবে বাংলাদেশের অন্যতম জনপ্রিয় অনলাইন বাস টিকিট বুকিং প্ল্যাটফর্ম। আমরা দিচ্ছি দ্রুত, নিরাপদ এবং সাশ্রয়ী ভ্রমণের নিশ্চয়তা।',

    // Auth / Login
    'auth.welcome': 'স্বাগতম!',
    'auth.welcome_back': 'আবার স্বাগতম!',
    'auth.create_account': 'নতুন একাউন্ট তৈরি করুন',
    'auth.login_subtitle': 'আপনার একাউন্টে লগইন করুন।',
    'auth.register_subtitle': 'নতুন একাউন্ট তৈরি করুন।',
    'auth.passenger': 'যাত্রী',
    'auth.staff': 'কাউন্টার / স্টাফ',
    'auth.email': 'ইমেইল এড্রেস',
    'auth.email_placeholder': 'ইমেইল অথবা ইউজারনেম',
    'auth.password': 'পাসওয়ার্ড',
    'auth.forgot': 'পাসওয়ার্ড ভুলে গেছেন?',
    'auth.signin': 'লগইন করুন',
    'auth.signup': 'একাউন্ট তৈরি করুন',
    'auth.staff_signin': 'স্টাফ লগইন',
    'auth.fullname': 'পুরো নাম',
    'auth.phone': 'মোবাইল নম্বর',
    'auth.google': 'গুগল দিয়ে লগইন করুন',
    'auth.or': 'অথবা',
    'auth.no_account': 'একাউন্ট নেই?',
    'auth.have_account': 'ইতিমধ্যেই একাউন্ট আছে?',
    'auth.hero_title': 'আপনার নিরাপদ ভ্রমণের শুরু এখানেই',
    'auth.hero_subtitle': 'আমাদের সাথে যুক্ত হয়ে আপনার ভ্রমণকে করুন আরও সহজ এবং আনন্দদায়ক।',
    'auth.stats_passengers': '৫০০০+ যাত্রী আমাদের সাথে ভ্রমণ করেছেন',
    'auth.register_success': 'নিবন্ধন সফল হয়েছে! আপনি এখন লগইন করতে পারেন।',
    'auth.register_failed': 'নিবন্ধন ব্যর্থ হয়েছে।',
    'auth.invalid_credentials': 'ভুল তথ্য প্রদান করা হয়েছে।',
    'auth.error_occurred': 'লগইন করার সময় একটি ত্রুটি ঘটেছে। আবার চেষ্টা করুন।',
    'auth.default_credentials': 'ডিফল্ট ক্রেডেনশিয়াল',
    'auth.admin': 'অ্যাডমিন',
    'auth.counter': 'কাউন্টার',

    // About Us
    'about.title': 'আমাদের সম্পর্কে',
    'about.subtitle': 'টিকিট লাগবে বাংলাদেশের একটি প্রিমিয়াম বাস সার্ভিস। আমরা যাত্রীদের সর্বোচ্চ আরাম এবং নিরাপত্তা নিশ্চিত করতে প্রতিশ্রুতিবদ্ধ।',
    'about.mission.title': 'আমাদের লক্ষ্য',
    'about.mission.desc': 'আমাদের লক্ষ্য হলো বাংলাদেশের যাতায়াত ব্যবস্থায় একটি নতুন মাত্রা যোগ করা। আমরা বিশ্বাস করি প্রতিটি যাত্রীর অধিকার আছে একটি নিরাপদ এবং আরামদায়ক ভ্রমণের। টিকিট লাগবে আধুনিক প্রযুক্তির সমন্বয়ে যাত্রীদের জন্য সহজ বুকিং এবং উন্নত সেবা প্রদান করে আসছে।',
    'about.why_choose.title': 'কেন আমাদের বেছে নেবেন?',
    'about.feature.safety': 'সর্বোচ্চ নিরাপত্তা',
    'about.feature.safety.desc': 'আমাদের প্রতিটি বাস জিপিএস ট্র্যাকিং এবং সিসিটিভি ক্যামেরা দ্বারা নিয়ন্ত্রিত।',
    'about.feature.staff': 'দক্ষ স্টাফ',
    'about.feature.staff.desc': 'আমাদের চালক এবং হেল্পাররা অত্যন্ত দক্ষ এবং যাত্রীবান্ধব।',
    'about.feature.routes': 'বিস্তৃত রুট',
    'about.feature.routes.desc': 'আমরা বাংলাদেশের প্রধান শহরগুলোতে নিয়মিত সার্ভিস প্রদান করি।',

    // Refund Policy
    'refund.title': 'রিফান্ড পলিসি',
    'refund.subtitle': 'টিকিট বাতিল এবং রিফান্ড সংক্রান্ত নিয়মাবলী নিচে দেওয়া হলো। বুকিংয়ের আগে অবশ্যই পড়ুন।',
    'refund.section1.title': '১. টিকিট বাতিলের সময়সীমা',
    'refund.section1.item1': 'যাত্রার নির্ধারিত সময়ের অন্তত ১২ ঘণ্টা আগে টিকিট বাতিল করলে ৮০% রিফান্ড পাওয়া যাবে।',
    'refund.section1.item2': 'যাত্রার ৬-১২ ঘণ্টা আগে টিকিট বাতিল করলে ৫০% রিফান্ড পাওয়া যাবে।',
    'refund.section1.item3': 'যাত্রার ৬ ঘণ্টার কম সময় বাকি থাকলে কোনো রিফান্ড দেওয়া হবে না।',
    'refund.section1.item4': 'ঈদের অগ্রিম টিকিটের ক্ষেত্রে কোনো রিফান্ড প্রযোজ্য নয়।',
    'refund.section2.title': '২. রিফান্ড প্রক্রিয়া',
    'refund.section2.item1': 'অনলাইন পেমেন্টের ক্ষেত্রে রিফান্ড ৩-৭ কার্যদিবসের মধ্যে আপনার মূল পেমেন্ট মেথডে (বিকাশ/নগদ/কার্ড) ফেরত দেওয়া হবে।',
    'refund.section2.item2': 'কাউন্টার থেকে কেনা টিকিটের ক্ষেত্রে সংশ্লিষ্ট কাউন্টারে যোগাযোগ করে রিফান্ড নিতে হবে।',
    'refund.section2.item3': 'রিফান্ড প্রসেসিংয়ের জন্য সার্ভিস চার্জ প্রযোজ্য হতে পারে।',
    'refund.section3.title': '৩. বিশেষ পরিস্থিতি',
    'refund.section3.desc': 'যদি টিকিট লাগবে কর্তৃপক্ষ কোনো কারণে ট্রিপ বাতিল করে, তবে যাত্রী ১০০% রিফান্ড পাবেন অথবা পরবর্তী কোনো ট্রিপে টিকিট পরিবর্তন করতে পারবেন। এক্ষেত্রে কোনো অতিরিক্ত চার্জ নেওয়া হবে না।',
    'refund.section4.title': '৪. যোগাযোগ',
    'refund.section4.desc': 'রিফান্ড সংক্রান্ত যেকোনো সমস্যার জন্য আমাদের হেল্পলাইন ০১৯০০-০০০০০০ নম্বরে কল করুন অথবা support@ticketlagbe.com এ ইমেইল করুন।',

    // Terms & Conditions
    'terms.title': 'শর্তাবলী',
    'terms.subtitle': 'টিকিট লাগবে ব্যবহারের জন্য নিচের শর্তাবলী মনোযোগ দিয়ে পড়ুন। টিকিট বুকিংয়ের মাধ্যমে আপনি এই শর্তাবলীতে সম্মত হচ্ছেন।',
    'terms.section1.title': '১. টিকিট বুকিং এবং পেমেন্ট',
    'terms.section1.item1': 'টিকিট বুকিংয়ের সময় সঠিক তথ্য (নাম, মোবাইল নম্বর, এনআইডি) প্রদান করতে হবে।',
    'terms.section1.item2': 'অনলাইন বুকিংয়ের ক্ষেত্রে পেমেন্ট সফল হওয়ার পর টিকিট কনফার্ম হবে।',
    'terms.section1.item3': 'টিকিট বুকিংয়ের পর মোবাইল ফোনে একটি কনফার্মেশন এসএমএস পাঠানো হবে।',
    'terms.section1.item4': 'টিকিট কাউন্টার থেকে টিকিট সংগ্রহের সময় বুকিং আইডি এবং এনআইডি দেখাতে হবে।',
    'terms.section2.title': '২. যাত্রা এবং সময়সূচী',
    'terms.section2.item1': 'যাত্রীদের বাসের নির্ধারিত সময়ের অন্তত ৩০ মিনিট আগে কাউন্টারে উপস্থিত হতে হবে।',
    'terms.section2.item2': 'অনিবার্য কারণে (যেমন: যানজট, যান্ত্রিক ত্রুটি, প্রাকৃতিক দুর্যোগ) বাসের সময় পরিবর্তন হতে পারে।',
    'terms.section2.item3': 'যাত্রী নির্ধারিত সময়ে উপস্থিত না থাকলে টিকিট বাতিল বলে গণ্য হবে এবং কোনো রিফান্ড দেওয়া হবে না।',
    'terms.section3.title': '৩. নিষিদ্ধ সামগ্রী এবং আচরণ',
    'terms.section3.item1': 'বাসের ভেতরে ধূমপান বা কোনো প্রকার মাদকদ্রব্য বহন করা সম্পূর্ণ নিষিদ্ধ।',
    'terms.section3.item2': 'বিস্ফোরক, আগ্নেয়াস্ত্র বা কোনো অবৈধ মালামাল বহন করা আইনত দণ্ডনীয় অপরাধ।',
    'terms.section3.item3': 'সহযাত্রীদের সাথে অশোভন আচরণ করলে যাত্রীকে বাস থেকে নামিয়ে দেওয়ার অধিকার কর্তৃপক্ষ সংরক্ষণ করে।',
    'terms.section4.title': '৪. দায়বদ্ধতা',
    'terms.section4.desc': 'যাত্রীদের ব্যক্তিগত মালামাল নিজ দায়িত্বে রাখতে হবে। মালামাল হারিয়ে গেলে কর্তৃপক্ষ দায়ী থাকবে না। তবে কোনো যান্ত্রিক ত্রুটির কারণে যাত্রা ব্যাহত হলে কর্তৃপক্ষ বিকল্প বাসের ব্যবস্থা করবে।',

    // HomePage
    'hero.title': 'আপনার নিরাপদ ভ্রমণের সঙ্গী',
    'hero.subtitle': 'টিকিট লাগবে - বাংলাদেশের এক প্রান্ত থেকে অন্য প্রান্তে আরামদায়ক এবং নিরাপদ যাতায়াত নিশ্চিত করতে আমরা বদ্ধপরিকর।',
    'hero.btn.book': 'টিকিট বুক করুন',
    'hero.btn.learn': 'আরও জানুন',
    'stats.experience': 'বছরের অভিজ্ঞতা',
    'stats.buses': 'আধুনিক বাস',
    'stats.drivers': 'দক্ষ চালক',
    'stats.passengers': 'সন্তুষ্ট যাত্রী',
    'features.title': 'কেন আমাদের বেছে নেবেন?',
    'features.subtitle': 'আমরা যাত্রীদের সর্বোচ্চ আরাম এবং নিরাপত্তা নিশ্চিত করতে আধুনিক প্রযুক্তি এবং দক্ষ জনবল ব্যবহার করি।',
    'feature.safety.title': 'সর্বোচ্চ নিরাপত্তা',
    'feature.safety.desc': 'আমাদের প্রতিটি বাসে জিপিএস ট্র্যাকিং এবং সিসিটিভি ক্যামেরা রয়েছে।',
    'feature.comfort.title': 'আরামদায়ক আসন',
    'feature.comfort.desc': 'বিলাসবহুল পুশ-ব্যাক সিট এবং পর্যাপ্ত লেগ-স্পেস নিশ্চিত করা হয়েছে।',
    'feature.booking.title': 'সহজ বুকিং',
    'feature.booking.desc': 'অনলাইনে মাত্র কয়েক মিনিটে আপনার পছন্দের আসন বুক করুন।',
    'routes.title': 'জনপ্রিয় রুটসমূহ',
    'routes.subtitle': 'দেশের প্রধান শহরগুলোতে আমাদের নিয়মিত সার্ভিস চালু রয়েছে।',
    'home.stats.routes': 'রুট সংখ্যা',
    'home.stats.safety': 'নিরাপত্তা রেটিং',
    'home.about.title': 'এক দশকেরও বেশি সময় ধরে আস্থার সাথে আপনার পাশে',
    'home.about.desc1': 'টিকিট লাগবে বাংলাদেশের পরিবহন খাতে একটি আস্থার নাম। দীর্ঘ এক দশকেরও বেশি সময় ধরে আমরা যাত্রীদের সর্বোচ্চ সেবা দিয়ে আসছি। আমাদের প্রতিটি যাত্রা শুরু হয় আপনার নিরাপত্তা এবং আরামের কথা মাথায় রেখে।',
    'home.about.desc2': 'আধুনিক প্রযুক্তির ব্যবহার এবং দক্ষ জনশক্তির সমন্বয়ে আমরা গড়ে তুলেছি একটি শক্তিশালী নেটওয়ার্ক, যা দেশের প্রতিটি প্রান্তে আপনাকে পৌঁছে দেয় সময়মতো।',
    'home.about.staff': 'দক্ষ কর্মী',
    'home.about.trips': 'প্রতিদিনের ট্রিপ',
    'home.feature.punctual.title': 'সময়নিষ্ঠ যাত্রা',
    'home.feature.punctual.desc': 'আমরা সময়ের মূল্য বুঝি। প্রতিটি ট্রিপ নির্ধারিত সময়ে শুরু এবং শেষ হয়।',
    'home.routes.view_all': 'সবগুলো দেখুন',
    'home.fare.info_title': 'ভাড়া সংক্রান্ত তথ্য',
    'home.fare.title': 'ভাড়া তালিকা ও স্টেশন নির্বাচন',
    'home.fare.desc': 'আপনার গন্তব্য অনুযায়ী ভাড়ার তালিকা দেখে নিন। আমরা দিচ্ছি সাশ্রয়ী মূল্যে প্রিমিয়াম ভ্রমণ অভিজ্ঞতা।',
    'home.fare.not_found': 'এই রুটে কোনো ভাড়া তথ্য পাওয়া যায়নি।',
    'home.fare.try_other': 'অন্য কোনো রুট নির্বাচন করে দেখুন।',
    'home.cta.title': 'আজই আপনার যাত্রা শুরু করুন',
    'home.cta.desc': 'আমাদের মোবাইল অ্যাপ ডাউনলোড করুন অথবা ওয়েবসাইট থেকে সরাসরি টিকিট বুক করুন।',
    'home.cta.btn': 'বুকিং শুরু করুন',
    'home.helpline': 'হেল্পলাইন',
    'home.route.from_price': 'থেকে',
    'home.stats.passengers_val': '৫ লাখ+',
    'home.stats.buses_val': '২০০+',
    'home.stats.routes_val': '৫০+',
    'home.stats.safety_val': '৪.৯/৫',
    'home.stats.experience_val': '১০+',
    'home.stats.staff_val': '৫০০+',
    'home.stats.trips_val': '১০০০+',
    'home.fare.departure': 'প্রস্থান স্টেশন',
    'home.fare.arrival': 'গন্তব্য স্টেশন',
    'home.fare.route': 'রুট',
    'home.fare.to': 'থেকে',
    'home.fare.non_ac': 'নন-এসি সার্ভিস',
    'home.fare.ac_standard': 'এসি স্ট্যান্ডার্ড',
    'home.fare.ac_premium': 'এসি প্রিমিয়াম',
    'home.fare.label': 'ভাড়া',
    'city.dhaka': 'ঢাকা',
    'city.chattogram': 'চট্টগ্রাম',
    'city.sylhet': 'সিলেট',
    'city.rajshahi': 'রাজশাহী',
    'city.coxsbazar': 'কক্সবাজার',
    'city.khulna': 'খুলনা',
    'city.rangpur': 'রংপুর',
    'city.cumilla': 'কুমিল্লা',
    'city.feni': 'ফেনী',
    'city.brahmanbaria': 'ব্রাহ্মণবাড়িয়া',
    'city.habiganj': 'হবিগঞ্জ',
    'city.tangail': 'টাঙ্গাইল',
    'city.sirajganj': 'সিরাজগঞ্জ',
    'city.bogra': 'বগুড়া',
    'city.gaibandha': 'গাইবান্ধা',
    'booking.route.origin': 'প্রস্থান',
    'booking.route.destination': 'গন্তব্য',
    'booking.route.stops': 'প্রধান স্টপেজ',
    'booking.route.duration': 'ভ্রমণ সময়',
    'booking.route.distance': 'দূরত্ব',
    'booking.bus.seats_left': 'আসন বাকি',
    'booking.bus.departure': 'প্রস্থান',
    'booking.bus.arrival': 'পৌঁছানো',
    'booking.payment.bKash': 'বিকাশ',
    'booking.payment.nagad': 'নগদ',
    'booking.payment.card': 'কার্ড',
    'booking.payment.pay_later': 'পেমেন্ট ছাড়া বুকিং',
    'booking.payment.redirecting': 'পেমেন্ট গেটওয়েতে পাঠানো হচ্ছে...',
    'booking.confirmation.portal': 'পোর্টাল',
    'booking.confirmation.print_note': 'এটি একটি ইলেকট্রনিক টিকিট। ভ্রমণের সময় এটি সাথে রাখুন।',
    'my_bookings.total_paid': 'মোট পরিশোধিত',
    'booking.error.name_required': 'নাম আবশ্যক',
    'booking.error.name_length': 'নাম অন্তত ৩ অক্ষরের হতে হবে',
    'booking.error.phone_required': 'ফোন নম্বর আবশ্যক',
    'booking.error.phone_invalid': 'ভুল ফোন নম্বর (যেমন: ০১৭XXXXXXXX)',
    'booking.cancel_confirm': 'আপনি কি নিশ্চিতভাবে এই বুকিংটি বাতিল করতে চান?',

    // BookingPortal
    'booking.search.title': 'টিকিট খুঁজুন',
    'booking.from': 'কোথা থেকে',
    'booking.to': 'কোথায় যাবেন',
    'booking.date': 'ভ্রমণের তারিখ',
    'booking.btn.search': 'বাস খুঁজুন',
    'booking.results.title': 'উপলব্ধ বাসসমূহ',
    'booking.seats.left': 'আসন বাকি',
    'booking.seats.select': 'আসন নির্বাচন করুন',
    'booking.seats.selected': 'নির্বাচিত আসন',
    'booking.total': 'মোট ভাড়া',
    'booking.btn.checkout': 'পেমেন্ট করুন',
    'booking.passenger.info': 'যাত্রীর তথ্য',
    'booking.passenger.name': 'নাম',
    'booking.passenger.phone': 'মোবাইল নম্বর',
    'booking.confirmation.title': 'বুকিং সফল হয়েছে!',
    'booking.confirmation.msg': 'আপনার টিকিট বুকিং সম্পন্ন হয়েছে। নিচের তথ্যগুলো সংরক্ষণ করুন।',
    'booking.id': 'বুকিং আইডি',
    'booking.status': 'অবস্থা',
    'booking.my_bookings': 'আমার বুকিং',

    // Admin/Counter
    'admin.title': 'অ্যাডমিন প্যানেল',
    'admin.profile.edit': 'অ্যাডমিন প্রোফাইল পরিবর্তন',
    'admin.profile.name': 'পূর্ণ নাম',
    'admin.profile.email': 'ইমেইল ঠিকানা',
    'admin.profile.save': 'পরিবর্তন সংরক্ষণ করুন',
    'admin.counter.add': 'নতুন কাউন্টার যোগ করুন',
    'admin.counter.name': 'কাউন্টারের নাম',
    'admin.counter.location': 'অবস্থান',
    'admin.counter.phone': 'ফোন নম্বর',
    'admin.counter.save': 'কাউন্টার যোগ করুন',
    'admin.bus.register': 'নতুন বাস নিবন্ধন করুন',
    'admin.bus.name': 'বাসের নাম',
    'admin.bus.reg_no': 'নিবন্ধন নম্বর',
    'admin.bus.driver': 'চালকের নাম',
    'admin.bus.driver_phone': 'চালকের ফোন',
    'admin.bus.last_maintenance': 'শেষ রক্ষণাবেক্ষণ',
    'admin.bus.next_maintenance': 'পরবর্তী রক্ষণাবেক্ষণ',
    'admin.bus.capacity': 'আসন সংখ্যা',
    'admin.bus.save': 'বাস নিবন্ধন করুন',
    'admin.route.add': 'নতুন রুট যোগ করুন',
    'admin.route.from': 'শুরু',
    'admin.route.to': 'শেষ',
    'admin.route.distance': 'দূরত্ব (কিমি)',
    'admin.route.duration': 'সময়',
    'admin.route.fare': 'ভাড়া (৳)',
    'admin.route.save': 'রুট যোগ করুন',
    'admin.user.add': 'নতুন ব্যবহারকারী যোগ করুন',
    'admin.user.role': 'ভূমিকা',
    'admin.user.password': 'পাসওয়ার্ড',
    'admin.user.save': 'ব্যবহারকারী তৈরি করুন',
    'admin.schedule.add': 'নতুন শিডিউল যোগ করুন',
    'admin.schedule.bus': 'বাস নির্বাচন করুন',
    'admin.schedule.route': 'রুট নির্বাচন করুন',
    'admin.schedule.departure': 'প্রস্থানের সময়',
    'admin.schedule.arrival': 'পৌঁছানোর সময়',
    'admin.schedule.date': 'তারিখ',
    'admin.schedule.save': 'শিডিউল যোগ করুন',
    'admin.nav.dashboard': 'ড্যাশবোর্ড',
    'admin.nav.buses': 'বাসসমূহ',
    'admin.nav.counters': 'কাউন্টারসমূহ',
    'admin.nav.users': 'ব্যবহারকারীগণ',
    'admin.nav.routes': 'রুটসমূহ',
    'admin.nav.schedules': 'শিডিউলসমূহ',
    'admin.nav.bookings': 'বুকিংসমূহ',
    'admin.nav.reports': 'রিপোর্ট',
    'admin.nav.settings': 'সেটিংস',
    'admin.nav.logout': 'লগআউট',
    'admin.search.placeholder': 'বুকিং খুঁজুন...',
    'admin.notifications': 'নোটিফিকেশন',
    'admin.stats.totalRevenue': 'মোট আয়',
    'admin.stats.onlineSales': 'অনলাইন বিক্রয়',
    'admin.stats.offlineSales': 'অফলাইন বিক্রয়',
    'admin.stats.ticketsSold': 'বিক্রিত টিকিট',
    'admin.stats.todaySales': 'আজকের বিক্রয়',
    'admin.stats.totalPassengers': 'মোট যাত্রী',
    'admin.stats.activeBuses': 'সক্রিয় বাস',
    'admin.stats.pendingIssues': 'বাকি সমস্যা',
    'admin.bookings.recent': 'সাম্প্রতিক বুকিং',
    'admin.table.bookingId': 'বুকিং আইডি',
    'admin.table.passenger': 'যাত্রী',
    'admin.table.phoneId': 'ফোন ও আইডি',
    'admin.table.route': 'রুট',
    'admin.table.time': 'সময়',
    'admin.table.status': 'অবস্থা',
    'admin.table.amount': 'পরিমাণ',
    'admin.table.action': 'অ্যাকশন',
    'admin.table.busNameReg': 'বাসের নাম ও রেজিস্ট্রেশন',
    'admin.table.driverDetails': 'চালকের তথ্য',
    'admin.table.maintenance': 'রক্ষণাবেক্ষণ',
    'admin.table.capacity': 'আসন সংখ্যা',
    'admin.table.last': 'সর্বশেষ',
    'admin.table.next': 'পরবর্তী',
    'admin.dashboard.overview': 'ড্যাশবোর্ড ওভারভিউ',
    'admin.dashboard.welcome': 'টিকিট লাগবে এডমিন প্যানেলে স্বাগতম।',
    'admin.dashboard.generateReport': 'রিপোর্ট তৈরি করুন',
    'admin.dashboard.todaySummary': 'আজকের বুকিং সারাংশ',
    'admin.dashboard.liveBusStatus': 'লাইভ বাসের অবস্থা',
    'admin.dashboard.quickActions': 'দ্রুত অ্যাকশন',
    'admin.dashboard.addBus': 'বাস যোগ করুন',
    'admin.dashboard.newRoute': 'নতুন রুট',
    'admin.dashboard.addCounter': 'কাউন্টার যোগ',
    'admin.dashboard.bookTicket': 'টিকিট বুকিং',
    'admin.manage.buses.title': 'বাস ব্যবস্থাপনা',
    'admin.manage.buses.desc': 'আপনার বহরের সকল বাস এখানে পরিচালনা করুন।',
    'admin.portal': 'পোর্টাল',
    'admin.fleet.fleetEfficiency': 'বহর দক্ষতা',
    'admin.table.busName': 'বাসের নাম',
    'admin.table.regNo': 'রেজিস্ট্রেশন নম্বর',
    'admin.table.lastService': 'শেষ সার্ভিস',
    'admin.table.nextService': 'পরবর্তী সার্ভিস',
    'admin.table.fuelEfficiency': 'জ্বালানি দক্ষতা',
    'admin.counter.counterPerformance': 'কাউন্টার পারফরম্যান্স',
    'admin.table.counterName': 'কাউন্টার নাম',
    'admin.table.target': 'লক্ষ্যমাত্রা',
    'admin.stats.direct_customer': 'সরাসরি কাস্টমার',
    'admin.manage.counters.title': 'কাউন্টার ব্যবস্থাপনা',
    'admin.manage.counters.desc': 'আপনার সকল কাউন্টার এখানে পরিচালনা করুন।',
    'admin.table.phone': 'ফোন',
    'admin.table.editDetails': 'বিস্তারিত সম্পাদনা',
    'admin.table.routePath': 'রুট পথ',
    'admin.table.distanceDuration': 'দূরত্ব ও সময়',
    'admin.table.standardRoute': 'স্ট্যান্ডার্ড রুট',
    'common.est': 'আনুমানিক',
    'admin.manage.schedules.title': 'শিডিউল ব্যবস্থাপনা',
    'admin.manage.schedules.desc': 'বাসের সময়সূচী এখানে পরিচালনা করুন।',
    'admin.table.dateTime': 'তারিখ ও সময়',
    'admin.table.availability': 'উপলব্ধতা',
    'admin.manage.users.title': 'ইউজার ব্যবস্থাপনা',
    'admin.manage.users.desc': 'সিস্টেম ব্যবহারকারীদের পরিচালনা করুন।',
    'admin.manage.owner': 'বাস মালিক',
    'admin.manage.owner.desc': 'বাস মালিকদের অ্যাকাউন্ট এবং তাদের বাসসমূহ পরিচালনা করুন।',
    'owner.nav.dashboard': 'ড্যাশবোর্ড',
    'owner.nav.counters': 'কাউন্টারসমূহ',
    'owner.nav.staff': 'স্টাফ পরিচালনা',
    'owner.nav.reports': 'রিপোর্ট',
    'owner.stats.totalRevenue': 'মোট আয়',
    'owner.stats.totalTickets': 'মোট টিকিট',
    'owner.stats.activeBuses': 'সক্রিয় বাস',
    'owner.stats.totalStaff': 'মোট স্টাফ',
    'owner.manage.counters.title': 'আমার কাউন্টারসমূহ',
    'owner.manage.counters.desc': 'আপনার বাসের জন্য নির্ধারিত কাউন্টারগুলো পরিচালনা করুন।',
    'owner.manage.staff.title': 'স্টাফ পরিচালনা',
    'owner.manage.staff.desc': 'আপনার কাউন্টারগুলোর জন্য স্টাফ যোগ বা বাদ দিন।',
    'owner.reports.title': 'আমার বাসের রিপোর্ট',
    'owner.reports.desc': 'আপনার বাসের আয় এবং পারফরম্যান্স রিপোর্ট দেখুন।',
    'admin.manage.users.initialize': 'ইউজার প্রোফাইল ইনিশিয়ালাইজ করুন',
    'admin.table.user': 'ব্যবহারকারী',
    'admin.table.email': 'ইমেইল',
    'admin.modal.counter.placeholder': 'কাউন্টার নির্বাচন করুন',
    'admin.stats.totalSales': 'মোট বিক্রয়',
    'admin.stats.totalTickets': 'মোট টিকিট',
    'admin.stats.counterSales': 'কাউন্টার বিক্রয়',
    'common.report': 'রিপোর্ট',
    'common.viewDetails': 'বিস্তারিত দেখুন',
    'admin.table.routeTime': 'রুট ও সময়',
    'admin.table.counterStaff': 'কাউন্টার ও স্টাফ',
    'common.travel': 'ভ্রমণ',
    'common.at': 'সময়',
    'common.online': 'অনলাইন',
    'common.staff': 'স্টাফ',
    'admin.booking.directWeb': 'সরাসরি ওয়েবসাইট',
    'admin.reports.title': 'রিপোর্ট',
    'admin.reports.revenue.title': 'আয় ও বিক্রয় রিপোর্ট',
    'admin.reports.revenue.desc': 'বিস্তারিত আয় এবং বিক্রয় প্রবণতা বিশ্লেষণ করুন।',
    'common.generateReport': 'রিপোর্ট তৈরি করুন',
    'admin.reports.efficiency.title': 'বাস ও বহর দক্ষতা',
    'admin.reports.efficiency.desc': 'বাসের পারফরম্যান্স এবং রক্ষণাবেক্ষণ ট্র্যাক করুন।',
    'admin.reports.counter.title': 'কাউন্টার পারফরম্যান্স',
    'admin.reports.counter.desc': 'বিভিন্ন কাউন্টারের বিক্রয় লক্ষ্যমাত্রা তুলনা করুন।',
    'admin.reports.sales.title': 'স্টাফ বিক্রয় রিপোর্ট',
    'admin.reports.sales.desc': 'কাউন্টার স্টাফদের ব্যক্তিগত বিক্রয় পারফরম্যান্স দেখুন।',
    'admin.settings.title': 'সিস্টেম সেটিংস',
    'admin.settings.general': 'সাধারণ সেটিংস',
    'admin.settings.maintenanceMode': 'রক্ষণাবেক্ষণ মোড',
    'admin.settings.maintenanceMode.desc': 'পুরো সিস্টেম রক্ষণাবেক্ষণ মোডে রাখুন।',
    'admin.settings.emailNotifications': 'ইমেইল নোটিফিকেশন',
    'admin.settings.emailNotifications.desc': 'গুরুত্বপূর্ণ আপডেটের জন্য ইমেইল অ্যালার্ট চালু করুন।',
    'admin.settings.initialization': 'ডেটা ইনিশিয়ালাইজেশন',
    'admin.settings.initialization.desc': 'সিস্টেমের প্রাথমিক ডেটা সেটআপ করুন।',
    'admin.settings.profile': 'প্রোফাইল সেটিংস',
    'admin.settings.editProfile': 'প্রোফাইল সম্পাদনা করুন',
    'admin.manage.counterUsers.title': 'কাউন্টার ইউজার ব্যবস্থাপনা',
    'admin.manage.counterUsers.desc': 'কাউন্টার স্টাফদের একাউন্ট পরিচালনা করুন।',
    'admin.table.userName': 'ব্যবহারকারীর নাম',
    'admin.table.assignedCounter': 'নির্ধারিত কাউন্টার',
    'common.remove': 'সরিয়ে ফেলুন',
    'common.filter': 'ফিল্টার',
    'common.export': 'এক্সপোর্ট',
    'common.noAddress': 'ঠিকানা নেই',
    'common.id': 'আইডি',
    'common.na': 'প্রযোজ্য নয়',
    'common.showing': 'দেখানো হচ্ছে',
    'common.today': 'আজ',
    'common.viewAll': 'সবগুলো দেখুন',
    'common.to': 'থেকে',
    'common.of': 'এর মধ্যে',
    'common.arriving': 'পৌঁছাচ্ছে',
    'common.seats': 'আসন',
    'common.save': 'সংরক্ষণ',
    'status.active': 'সক্রিয়',
    'status.maintenance': 'রক্ষণাবেক্ষণ',
    'status.inactive': 'নিষ্ক্রিয়',
    'admin.table.id': 'বুকিং আইডি',
    'admin.table.counter': 'কাউন্টার',
    'admin.table.staff': 'স্টাফ',
    'admin.table.actions': 'অ্যাকশন',
    'admin.action.print': 'টিকিট প্রিন্ট',
    'admin.action.cancel': 'বুকিং বাতিল',
    'admin.action.view': 'বিস্তারিত দেখুন',
    'admin.action.edit': 'সম্পাদনা',
    'admin.action.delete': 'মুছে ফেলুন',
    'admin.action.save': 'সংরক্ষণ',
    'admin.action.cancel_btn': 'বাতিল',
    'admin.action.close': 'বন্ধ করুন',
    'admin.report.generate': 'রিপোর্ট তৈরি করুন',
    'admin.report.revenue': 'আয় রিপোর্ট',
    'admin.report.efficiency': 'বাস দক্ষতা',
    'admin.report.performance': 'কাউন্টার পারফরম্যান্স',
    'admin.report.staff_sales': 'কাউন্টার ও স্টাফ বিক্রয়',
    'admin.report.summary': 'ড্যাশবোর্ড সারসংক্ষেপ',
    'admin.report.counter_summary': 'কাউন্টার ভিত্তিক সারসংক্ষেপ',
    'admin.report.channel': 'কাউন্টার/চ্যানেল',
    'admin.report.metric': 'মেট্রিক',
    'admin.report.value': 'মান',
    'admin.report.change': 'পরিবর্তন',
    'admin.report.date_issued': 'ইস্যুর তারিখ',
    'admin.report.issued_by': 'ইস্যুকারী',
    'admin.report.title': 'টিকিট লাগবে - অ্যাডমিন পোর্টাল',
    'admin.report.generated_on': 'তৈরির সময়:',
    'admin.report.type': 'রিপোর্টের ধরন:',

    // Admin Modals & Details
    'admin.modal.busDetails': 'বাসের বিস্তারিত',
    'admin.modal.maintenanceHistory': 'রক্ষণাবেক্ষণের ইতিহাস',
    'admin.modal.driverInfo': 'চালকের তথ্য',
    'admin.modal.regNo': 'রেজিস্ট্রেশন নম্বর',
    'admin.modal.status': 'অবস্থা',
    'admin.modal.capacity': 'আসন সংখ্যা',
    'admin.modal.lastServiced': 'সর্বশেষ সার্ভিস',
    'admin.modal.nextScheduled': 'পরবর্তী শিডিউল',
    'admin.modal.editBus': 'বাস সম্পাদনা',
    'admin.modal.registerBus': 'নতুন বাস নিবন্ধন',
    'admin.modal.busName': 'বাসের নাম',
    'admin.modal.driverName': 'চালকের নাম',
    'admin.modal.driverPhone': 'চালকের ফোন',
    'admin.modal.assignedRoute': 'নির্ধারিত রুট',
    'admin.modal.capacitySeats': 'বাসের ক্ষমতা (আসন)',
    'admin.modal.lastMaintenance': 'সর্বশেষ রক্ষণাবেক্ষণ',
    'admin.modal.nextMaintenance': 'পরবর্তী রক্ষণাবেক্ষণ',
    'admin.modal.addRoute': 'নতুন রুট যোগ করুন',
    'admin.modal.from': 'কোথা থেকে',
    'admin.modal.to': 'কোথায়',
    'admin.modal.distance': 'দূরত্ব',
    'admin.modal.duration': 'সময়',
    'admin.modal.fareBdt': 'ভাড়া (টাকা)',
    'admin.modal.addSchedule': 'নতুন শিডিউল যোগ করুন',
    'admin.modal.selectBus': 'বাস নির্বাচন করুন',
    'admin.modal.selectRoute': 'রুট নির্বাচন করুন',
    'admin.modal.date': 'তারিখ',
    'admin.modal.seats': 'আসন',
    'admin.modal.departure': 'প্রস্থান',
    'admin.modal.arrival': 'পৌঁছানো',
    'admin.modal.addCounterUser': 'কাউন্টার ইউজার যোগ করুন',
    'admin.modal.fullName': 'পুরো নাম',
    'admin.modal.email': 'ইমেইল',
    'admin.modal.password': 'পাসওয়ার্ড',
    'admin.modal.assignCounter': 'কাউন্টার নির্ধারণ করুন',
    'admin.modal.addNewUser': 'নতুন ইউজার যোগ করুন',
    'admin.modal.role': 'রোল',
    'admin.modal.editProfile': 'এডমিন প্রোফাইল সম্পাদনা',
    'admin.modal.addCounter': 'নতুন কাউন্টার যোগ করুন',
    'admin.modal.counterName': 'কাউন্টার নাম',
    'admin.modal.location': 'অবস্থান',
    'admin.modal.phone': 'ফোন নম্বর',

    // Counter Dashboard
    'counter.nav.dashboard': 'ড্যাশবোর্ড',
    'counter.nav.sellTickets': 'টিকিট বিক্রয়',
    'counter.nav.myBookings': 'আমার বুকিং',
    'counter.portal.title': 'কাউন্টার পোর্টাল',
    'counter.portal': 'পোর্টাল',
    'counter.sell.subtitle': 'টিকিট বিক্রয় করুন এবং যাত্রীদের তথ্য সংগ্রহ করুন',
    'counter.sell.searchPlaceholder': 'বাস বা রুট খুঁজুন...',
    'counter.sell.bookNow': 'বুক করুন',
    'counter.bookings.subtitle': 'আপনার কাউন্টার থেকে করা সকল বুকিং এখানে দেখুন',
    'counter.bookings.searchPlaceholder': 'বুকিং আইডি বা নাম দিয়ে খুঁজুন...',
    'counter.dashboard.dailySalesSummary': 'দৈনিক বিক্রয় সারাংশ',
    'counter.dashboard.overviewToday': 'আজকের ওভারভিউ -',
    'counter.dashboard.totalCombined': 'মোট অনলাইন ও অফলাইন',
    'counter.dashboard.onlineMobile': 'অনলাইন ও মোবাইল',
    'counter.dashboard.digitalPayments': 'ডিজিটাল পেমেন্ট',
    'counter.dashboard.offlineCash': 'অফলাইন ও ক্যাশ',
    'counter.dashboard.cashAtCounter': 'কাউন্টারে নগদ পেমেন্ট',
    'counter.dashboard.salesByService': 'সার্ভিস অনুযায়ী বিক্রয়',
    'counter.dashboard.acServices': 'এসি সার্ভিস',
    'counter.dashboard.nonAcServices': 'নন-এসি সার্ভিস',
    'counter.dashboard.downloadReport': 'রিপোর্ট ডাউনলোড করুন',
    'counter.dashboard.todaysSchedule': 'আজকের সময়সূচী',
    'counter.dashboard.sellTicket': 'টিকিট বিক্রয়',
    'counter.dashboard.vsYesterday': '+১২.৫% গতকালের তুলনায়',
    'counter.dashboard.acServicesStats': '৳{amount} ({count} {tickets})',
    'counter.dashboard.nonAcServicesStats': '৳{amount} ({count} {tickets})',
    'counter.ticket.printTitle': 'টিকিট প্রিন্ট করুন',
    'counter.ticket.id': 'টিকিট আইডি',
    'counter.ticket.passenger': 'যাত্রী',
    'counter.ticket.phone': 'ফোন',
    'counter.ticket.passengerId': 'যাত্রী আইডি',
    'counter.ticket.date': 'তারিখ',
    'counter.ticket.seatWise': 'আসন ভিত্তিক যাত্রী',
    'counter.ticket.address': 'ঠিকানা',
    'counter.ticket.bus': 'বাস',
    'counter.ticket.route': 'রুট',
    'counter.ticket.seats': 'আসন',
    'counter.ticket.totalPaid': 'মোট পরিশোধিত',
    'counter.ticket.printNow': 'প্রিন্ট করুন',
    'counter.ticket.download': 'ডাউনলোড',
    'counter.ticket.close': 'বন্ধ করুন',
    'counter.download.confirmTitle': 'ডাউনলোড ফরম্যাট নিশ্চিত করুন',
    'counter.download.confirmMsg': 'দয়া করে আপনার পছন্দের ফরম্যাট নির্বাচন করুন। টিকিটে একটি কিউআর কোড (QR Code) রয়েছে যা ভ্রমণের সময় যাত্রী যাচাইয়ের জন্য প্রয়োজন।',
    'counter.download.noticeTitle': 'যাচাইকরণ বিজ্ঞপ্তি',
    'counter.download.noticeMsg': 'কিউআর কোডটি অবশ্যই পরিষ্কারভাবে পাঠযোগ্য হতে হবে। সেরা প্রিন্টিং কোয়ালিটি এবং যাচাইকরণের নির্ভরযোগ্যতার জন্য আমরা পিডিএফ (PDF) ফরম্যাট সুপারিশ করি।',
    'counter.download.image': 'ছবি',
    'counter.download.imageFormat': 'পিএনজি ফরম্যাট',
    'counter.download.document': 'ডকুমেন্ট',
    'counter.download.documentFormat': 'পিডিএফ ফরম্যাট',
    'counter.notifications.title': 'বিজ্ঞপ্তি',
    'counter.notifications.markAllRead': 'সবগুলো পঠিত হিসেবে চিহ্নিত করুন',
    'counter.notifications.empty': 'কোন নতুন বিজ্ঞপ্তি নেই',
    'counter.notifications.viewAll': 'সবগুলো দেখুন',
    'counter.search.placeholder': 'খুঁজুন...',
    'counter.alert.fill_details': 'দয়া করে সব তথ্য পূরণ করুন এবং অন্তত একটি সিট নির্বাচন করুন।',
    'counter.alert.seat_details': 'দয়া করে সিট {seat}-এর তথ্য পূরণ করুন',
    'counter.alert.reserve_success': 'বুকিং সফলভাবে সংরক্ষিত হয়েছে! বৈধ থাকবে {time} পর্যন্ত',
    'counter.alert.confirm_success': 'টিকিট সফলভাবে নিশ্চিত করা হয়েছে!',
    'counter.alert.cancel_confirm': 'আপনি কি নিশ্চিতভাবে এই বুকিংটি বাতিল করতে চান?',
    'counter.alert.cancel_success': 'টিকিট সফলভাবে বাতিল করা হয়েছে!',
    'counter.alert.error': 'ত্রুটি: {message}',
    'counter.alert.failed_sell': 'টিকিট বিক্রয় করতে ব্যর্থ হয়েছে। আবার চেষ্টা করুন।',
    'counter.alert.failed_confirm': 'টিকিট নিশ্চিত করতে ব্যর্থ হয়েছে।',
    'counter.alert.failed_cancel': 'টিকিট বাতিল করতে ব্যর্থ হয়েছে।',
    'counter.alert.failed_download': 'ডাউনলোড করতে ব্যর্থ হয়েছে। আবার চেষ্টা করুন।',
    'counter.alert.failed_pdf': 'পিডিএফ তৈরি করতে ব্যর্থ হয়েছে।',
    'report.sales_report': 'বিক্রয় রিপোর্ট',
    'report.summary_stats': 'পরিসংখ্যান সারাংশ',
    'report.metric': 'মেট্রিক',
    'report.value': 'মান',
    'report.detailed_bookings': 'বিস্তারিত বুকিং',
    'counter.bookings.allStatus': 'সব অবস্থা',
    'counter.bookings.allDates': 'সব তারিখ',
    'counter.bookings.exportCsv': 'CSV এক্সপোর্ট',
    'admin.table.ticketId': 'টিকিট আইডি',
    'admin.table.busRoute': 'বাস ও রুট',
    'admin.table.seats': 'আসন',
    'table.status.confirmed': 'নিশ্চিত',
    'table.status.reserved': 'সংরক্ষিত',
    'table.status.cancelled': 'বাতিল',
    'table.status.pending': 'অপেক্ষমান',
    'counter.bookings.noResults': 'কোন বুকিং পাওয়া যায়নি।',
    'counter.sell.modalTitle': 'টিকিট বুকিং',
    'counter.sell.selectSeats': 'আসন নির্বাচন করুন',
    'common.total': 'মোট',
    'counter.sell.passengerName': 'যাত্রীর নাম',
    'counter.sell.fullNamePlaceholder': 'পুরো নাম লিখুন',
    'counter.sell.phoneNumber': 'ফোন নম্বর',
    'counter.sell.passengerId': 'যাত্রী আইডি (ঐচ্ছিক)',
    'counter.sell.idPlaceholder': 'এনআইডি বা জন্ম নিবন্ধন',
    'counter.sell.address': 'ঠিকানা',
    'counter.sell.addressPlaceholder': 'বর্তমান ঠিকানা',
    'counter.sell.individualDetails': 'প্রতিটি আসনের আলাদা তথ্য দিন',
    'common.seat': 'আসন',
    'counter.sell.bookingType': 'বুকিংয়ের ধরন',
    'common.purchase': 'সরাসরি ক্রয়',
    'common.reserveNoMoney': 'শুধু রিজার্ভেশন (টাকা ছাড়া)',
    'counter.sell.reservationExpiry': 'রিজার্ভেশনের মেয়াদ (মিনিট)',
    'counter.sell.paymentMethod': 'পেমেন্ট পদ্ধতি',
    'counter.sell.totalAmount': 'মোট পরিমাণ',
    'counter.sell.confirmPrint': 'নিশ্চিত ও প্রিন্ট করুন',
    'counter.sell.reserveSeat': 'আসন রিজার্ভ করুন',
    'common.tickets': 'টিকিট',
    'counter.title': 'কাউন্টার',
    'common.coming_soon': 'শীঘ্রই আসছে',
    'common.name': 'নাম',
    'common.phone': 'ফোন',
    'admin.table.busInfo': 'বাসের তথ্য',
    'admin.table.departure': 'প্রস্থান',
    'admin.table.availableSeats': 'উপলব্ধ আসন',
    'admin.table.fare': 'ভাড়া',

    // Common Dashboard
    'dashboard.header.notifications': 'নোটিফিকেশন',
    'dashboard.header.searchPlaceholder': 'টিকিট খুঁজুন...',
    'dashboard.header.markAllRead': 'সবগুলো পঠিত হিসেবে চিহ্নিত করুন',
    'dashboard.header.noNotifications': 'কোন নোটিফিকেশন নেই',
    'dashboard.header.viewAllNotifications': 'সব নোটিফিকেশন দেখুন',
    'dashboard.header.backToHome': 'হোমে ফিরে যান',

    // Table & Actions
    'table.header.id': 'আইডি',
    'table.header.passenger': 'যাত্রী',
    'table.header.route': 'রুট',
    'table.header.time': 'সময়',
    'table.header.status': 'অবস্থা',
    'table.header.amount': 'পরিমাণ',
    'table.header.action': 'অ্যাকশন',
    'table.header.busInfo': 'বাসের তথ্য',
    'table.header.departure': 'প্রস্থান',
    'table.header.availableSeats': 'উপলব্ধ আসন',
    'table.action.edit': 'সম্পাদনা',
    'table.action.delete': 'মুছে ফেলুন',
    'table.action.view': 'দেখুন',
    'table.action.sellTicket': 'টিকিট বিক্রয়',
    'table.action.bookNow': 'এখনই বুক করুন',

    // Status
    'status.confirmed': 'নিশ্চিত',
    'status.cancelled': 'বাতিল',
    'status.reserved': 'সংরক্ষিত',
    'status.onTime': 'সময়মত',
    'status.delayed': 'বিলম্বিত',

    // Buttons
    'button.saveChanges': 'পরিবর্তন সংরক্ষণ করুন',
    'button.addCounter': 'কাউন্টার যোগ করুন',
    'button.addUser': 'ব্যবহারকারী যোগ করুন',
    'button.registerBus': 'বাস নিবন্ধন করুন',
    'button.addRoute': 'রুট যোগ করুন',
    'button.addSchedule': 'সময়সূচী যোগ করুন',
    'button.cancel': 'বাতিল',
    'button.confirm': 'নিশ্চিত করুন',
    'button.printTicket': 'টিকিট প্রিন্ট করুন',
    'button.downloadPDF': 'পিডিএফ ডাউনলোড করুন',
    'button.viewAll': 'সব দেখুন',
    'button.viewAllNotifications': 'সব নোটিফিকেশন দেখুন',
    'button.backToHome': 'হোমে ফিরে যান',

    // UserProfile
    'profile.title': 'ব্যবহারকারীর প্রোফাইল',
    'profile.edit': 'প্রোফাইল সম্পাদনা করুন',
    'profile.logout': 'লগআউট',
    'profile.back': 'ফিরে যান',
    'profile.member_since': 'সদস্যপদ শুরু:',
    'profile.total_trips': 'মোট ভ্রমণ',
    'profile.points': 'পয়েন্ট',
    'profile.saved_cards': 'সংরক্ষিত কার্ড',
    'profile.recent_activity': 'সাম্প্রতিক কার্যক্রম',
    'profile.view_all': 'সব দেখুন',
    'profile.account_settings': 'অ্যাকাউন্ট সেটিংস',
    'profile.security': 'নিরাপত্তা',
    'profile.security_desc': 'পাসওয়ার্ড এবং ২এফএ',
    'profile.notifications': 'বিজ্ঞপ্তি',
    'profile.notifications_desc': 'ইমেল এবং এসএমএস অ্যালার্ট',
    'profile.payment_methods': 'পেমেন্ট পদ্ধতি',
    'profile.payment_methods_desc': 'আপনার কার্ড পরিচালনা করুন',
    'profile.privacy': 'গোপনীয়তা',
    'profile.privacy_desc': 'ডেটা এবং দৃশ্যমানতা',
    'profile.membership_id': 'সদস্যপদ আইডি:',
    'profile.expires': 'মেয়াদ শেষ:',
    'profile.card_holder': 'কার্ড হোল্ডার',
    'profile.platinum': 'প্লাটিনাম',
    'profile.premium_member': 'প্রিমিয়াম সদস্য',
    'profile.administrator': 'প্রশাসক',
    'profile.counter_staff': 'কাউন্টার স্টাফ',
    'profile.activity.booking': 'বুকিং',
    'profile.activity.payment': 'পেমেন্ট',
    'profile.activity.support': 'সাপোর্ট',
    'profile.activity.confirmed': 'নিশ্চিত',
    'profile.activity.success': 'সফল',
    'profile.activity.resolved': 'সমাধান করা হয়েছে',
    'profile.activity.hours_ago': 'ঘণ্টা আগে',
    'profile.activity.yesterday': 'গতকাল',
    'profile.activity.days_ago': 'দিন আগে',
    'profile.quick_stats': 'সংক্ষিপ্ত পরিসংখ্যান',
    'admin.manage.routes.title': 'রুট লিস্ট',
    'admin.manage.routes.desc': 'আপনার সকল রুট এখানে পরিচালনা করুন।',
    'admin.modal.addUser': 'নতুন ব্যবহারকারী যোগ করুন',
    'admin.stats.target': 'লক্ষ্যমাত্রা',
    'admin.table.location': 'অবস্থান',
    'admin.table.role': 'ভূমিকা',
    'booking.passenger.address': 'ঠিকানা',
    'booking.route': 'রুট',
    'common.available': 'উপলব্ধ',
    'common.booked': 'বুকড',
    'common.cancel': 'বাতিল',
    'common.confirm': 'নিশ্চিত',
    'common.confirm_delete': 'আপনি কি নিশ্চিত যে আপনি এই আইটেমটি মুছে ফেলতে চান?',
    'common.confirmed': 'নিশ্চিত',
    'common.delete': 'মুছে ফেলুন',
    'common.edit': 'সম্পাদনা',
    'common.reserved': 'সংরক্ষিত',
    'common.selected': 'নির্বাচিত',
    'common.view': 'দেখুন',
    'counter.sell.offlineCash': 'অফলাইন ও ক্যাশ',
    'counter.sell.onlineMobile': 'অনলাইন ও মোবাইল',
    'footer.copyright': 'টিকিট লাগবে',
    'table.header.date': 'তারিখ',
    'admin.alert.counter_success': 'কাউন্টার সফলভাবে যোগ করা হয়েছে!',
    'admin.alert.counter_fail': 'কাউন্টার যোগ করতে ব্যর্থ হয়েছে',
    'admin.alert.counter_user_success': 'কাউন্টার ইউজার প্রোফাইল সফলভাবে তৈরি করা হয়েছে!',
    'admin.alert.counter_user_fail': 'কাউন্টার ইউজার তৈরি করতে ব্যর্থ হয়েছে',
    'admin.alert.user_success': 'ব্যবহারকারী সফলভাবে তৈরি করা হয়েছে!',
    'admin.alert.user_fail': 'ব্যবহারকারী তৈরি করতে ব্যর্থ হয়েছে',
    'admin.alert.bus_success': 'বাস সফলভাবে নিবন্ধিত হয়েছে!',
    'admin.alert.bus_fail': 'বাস নিবন্ধন করতে ব্যর্থ হয়েছে',
    'admin.alert.route_success': 'রুট সফলভাবে যোগ করা হয়েছে!',
    'admin.alert.route_fail': 'রুট যোগ করতে ব্যর্থ হয়েছে',
    'admin.alert.item_delete_success': 'আইটেমটি সফলভাবে মুছে ফেলা হয়েছে!',
    'admin.alert.item_delete_fail': 'আইটেমটি মুছতে ব্যর্থ হয়েছে',
    'admin.alert.user_update_success': 'ব্যবহারকারীর তথ্য সফলভাবে সংরক্ষিত হয়েছে!',
    'admin.alert.user_update_fail': 'ব্যবহারকারীর তথ্য সংরক্ষণ করতে ব্যর্থ হয়েছে',
    'admin.alert.bus_update_success': 'বাসের তথ্য সফলভাবে আপডেট করা হয়েছে!',
    'admin.alert.bus_update_fail': 'বাসের তথ্য সংরক্ষণ করতে ব্যর্থ হয়েছে',
    'admin.alert.counter_update_success': 'কাউন্টারের তথ্য সফলভাবে আপডেট করা হয়েছে!',
    'admin.alert.counter_update_fail': 'কাউন্টারের তথ্য সংরক্ষণ করতে ব্যর্থ হয়েছে',
    'admin.alert.route_update_success': 'রুটের তথ্য সফলভাবে আপডেট করা হয়েছে!',
    'admin.alert.route_update_fail': 'রুটের তথ্য সংরক্ষণ করতে ব্যর্থ হয়েছে',
    'admin.alert.schedule_success': 'শিডিউল সফলভাবে যোগ করা হয়েছে!',
    'admin.alert.schedule_fail': 'শিডিউল যোগ করতে ব্যর্থ হয়েছে',
    'admin.alert.schedule_update_success': 'শিডিউল সফলভাবে আপডেট করা হয়েছে!',
    'admin.alert.schedule_update_fail': 'শিডিউল আপডেট করতে ব্যর্থ হয়েছে',
    'admin.alert.init_success': 'ডিফল্ট ইউজার প্রোফাইলগুলো ইতিমধ্যেই লোকাল স্টেটে ইনিশিয়ালাইজ করা আছে।',
    'admin.alert.report_fail': 'রিপোর্ট তৈরি করতে ব্যর্থ হয়েছে। আবার চেষ্টা করুন।',
    'admin.report.summary_title': 'সাধারণ ড্যাশবোর্ড সারসংক্ষেপ',
    'admin.report.revenue_title': 'আয় রিপোর্ট',
    'admin.report.efficiency_title': 'বাস দক্ষতা',
    'admin.report.performance_title': 'কাউন্টার পারফরম্যান্স',
    'admin.report.staff_sales_title': 'কাউন্টার ও স্টাফ বিক্রয়',
  },
  en: {
    // Header & General
    'nav.home': 'Home',
    'nav.about': 'About Us',
    'nav.terms': 'Terms',
    'nav.refund': 'Refund Policy',
    'nav.login': 'Login',
    'nav.admin': 'Admin',
    'nav.owner': 'Bus Owner',
    'nav.counter': 'Counter',
    'nav.logout': 'Logout',
    'footer.rights': 'All rights reserved.',
    'btn.back': 'Go Back',
    'btn.close': 'Close',
    'btn.home': 'Back to Home',
    'brand.name': 'Ticket Lagbe',
    'brand.subtitle': 'Premium Bus Service',

    // Chat
    'chat.welcome': 'Assalamu Alaikum! Welcome to Ticket Lagbe Support Center. How can I help you today?',
    'chat.error': 'Sorry, the chat service is not working at the moment. Please check the API Key.',
    'chat.header.title': 'Customer Support',
    'chat.header.subtitle': 'Ticket Lagbe AI',
    'chat.input.placeholder': 'Type your question...',
    'chat.quick.timings': 'Bus Timings',
    'chat.quick.routes': 'Routes',
    'chat.quick.fare': 'Fare',
    'chat.quick.timings.query': 'I want to know bus timings',
    'chat.quick.routes.query': 'What are your routes?',
    'chat.quick.fare.query': 'What is the ticket fare?',

    // Footer
    'footer.contact': 'Contact',
    'footer.links': 'Links',
    'footer.about_desc': 'Ticket Lagbe is a premium bus service in Bangladesh. We are committed to ensuring maximum comfort and safety for passengers.',
    'footer.address': 'Dhaka, Bangladesh',
    'footer.home': 'Home',
    'footer.booking': 'Booking',
    'footer.support': 'Support',
    'nav.offers': 'Offers',
    'nav.profile': 'Profile',
    'nav.passenger_dashboard': 'Passenger Dashboard',
    'nav.profile_profile': 'Profile',
    'passenger.dashboard.title': 'Passenger Dashboard',
    'passenger.dashboard.welcome': 'Welcome, {{name}}!',
    'passenger.dashboard.subtitle': 'Manage your trips and bookings from here.',
    'passenger.dashboard.upcoming_trips': 'Upcoming Trips',
    'passenger.dashboard.past_trips': 'Past Trips',
    'passenger.dashboard.loyalty_points': 'Loyalty Points',
    'passenger.dashboard.book_now': 'Book Now',
    'passenger.dashboard.no_trips': 'You have no upcoming trips.',
    'passenger.dashboard.quick_actions': 'Quick Actions',
    'passenger.dashboard.track_bus': 'Track Bus',
    'passenger.dashboard.cancel_ticket': 'Cancel Ticket',
    'passenger.dashboard.support': 'Support',
    'passenger.dashboard.profile_summary': 'Profile Summary',
    'passenger.dashboard.member_id': 'Member ID',
    'passenger.dashboard.total_spent': 'Total Spent',
    'passenger.dashboard.trips_completed': 'Trips Completed',
    'passenger.dashboard.transactions': 'Transaction History',
    'passenger.dashboard.change_password': 'Change Password',
    'passenger.dashboard.old_password': 'Old Password',
    'passenger.dashboard.new_password': 'New Password',
    'passenger.dashboard.confirm_password': 'Confirm Password',
    'passenger.dashboard.password_mismatch': 'Passwords do not match',
    'passenger.dashboard.password_success': 'Password changed successfully',
    'passenger.dashboard.password_error': 'Failed to change password',
    'passenger.dashboard.track_bus_title': 'Bus Tracking',
    'passenger.dashboard.bus_status': 'Bus Status',
    'passenger.dashboard.current_speed': 'Current Speed',
    'passenger.dashboard.next_stop': 'Next Stop',
    'passenger.dashboard.last_updated': 'Last Updated',
    'passenger.dashboard.transaction_id': 'Transaction ID',
    'passenger.dashboard.transaction_type': 'Type',
    'passenger.dashboard.transaction_method': 'Method',
    'passenger.dashboard.transaction_amount': 'Amount',
    'passenger.dashboard.transaction_date': 'Date',
    'passenger.dashboard.no_transactions': 'No transactions found',
    'passenger.dashboard.refund_ticket': 'Refund Ticket',
    'passenger.dashboard.refund_confirm': 'Are you sure you want to request a refund for this ticket?',
    'passenger.dashboard.refund_success': 'Refund request submitted successfully.',
    'passenger.dashboard.refund_failed': 'Failed to submit refund request.',
    'passenger.dashboard.refund_status': 'Refund Requested',
    'booking.hero.title': 'Your Trusted Companion for Safe Travel',
    'booking.hero.subtitle': 'Book your preferred seat from the best bus services in the country in just a few clicks.',
    'booking.search.from_placeholder': 'Departure City',
    'booking.search.to_placeholder': 'Destination City',
    'booking.results.count': 'Available Buses',
    'booking.results.change': 'Change Search',
    'booking.results.per_person': 'Per Person',
    'booking.results.select_seats': 'Select Seats',
    'booking.seats.title': 'Select Your Seats',
    'booking.seats.available': 'Available',
    'booking.seats.booked': 'Booked',
    'booking.summary.title': 'Booking Summary',
    'booking.summary.bus': 'Bus',
    'booking.summary.seats': 'Seats',
    'booking.summary.none': 'None',
    'booking.summary.total': 'Total Fare',
    'booking.summary.proceed': 'Proceed to Checkout',
    'booking.passenger.details': 'Passenger Details',
    'booking.passenger.fullname': 'Full Name',
    'booking.passenger.name_placeholder': 'Enter your name',
    'booking.passenger.phone_placeholder': '01XXX-XXXXXX',
    'booking.passenger.email': 'Email Address',
    'booking.passenger.identity': 'NID / Birth Cert / Passport',
    'booking.passenger.district': 'District',
    'booking.passenger.thana': 'Thana',
    'booking.passenger.postOffice': 'Post Office & Code',
    'booking.passenger.village': 'Village',
    'booking.payment.method': 'Payment Method',
    'booking.payment.secured': 'Secured by SSLCommerz',
    'booking.payment.confirm_pay': 'Confirm & Pay',
    'booking.confirmation.subtitle': 'Thank you for choosing Ticket Lagbe. Your ticket is ready.',
    'booking.confirmation.no': 'Confirmation No.',
    'booking.confirmation.passenger': 'Passenger',
    'booking.confirmation.phone': 'Phone',
    'booking.confirmation.bus': 'Bus Service',
    'booking.confirmation.seats': 'Seats',
    'booking.confirmation.departure': 'Departure',
    'booking.confirmation.total': 'Total Paid',
    'booking.confirmation.issued_by': 'Issued By',
    'booking.confirmation.date_issued': 'Date Issued',
    'booking.confirmation.print': 'Print Ticket',
    'booking.confirmation.back': 'Back to Home',
    'my_bookings.title': 'My Bookings',
    'my_bookings.subtitle': 'Manage your past and upcoming travels',
    'my_bookings.new_trip': 'Book New Trip',
    'my_bookings.upcoming': 'Upcoming',
    'my_bookings.completed': 'Completed',
    'my_bookings.cancelled': 'Cancelled',
    'my_bookings.view_details': 'View Details',
    'my_bookings.cancel_booking': 'Cancel Booking',
    'my_bookings.details_title': 'Booking Details',
    'my_bookings.close': 'Close',
    'footer.about_title': 'About Us',
    'footer.about_desc_portal': 'Ticket Lagbe is one of the most popular online bus ticket booking platforms in Bangladesh. We provide fast, safe and affordable travel assurance.',

    // Auth / Login
    'auth.welcome': 'Welcome!',
    'auth.welcome_back': 'Welcome Back!',
    'auth.create_account': 'Create Account',
    'auth.login_subtitle': 'Login to your account.',
    'auth.register_subtitle': 'Create a new account.',
    'auth.passenger': 'Passenger',
    'auth.staff': 'Counter / Staff',
    'auth.email': 'Email Address',
    'auth.email_placeholder': 'Email or Username',
    'auth.password': 'Password',
    'auth.forgot': 'Forgot Password?',
    'auth.signin': 'Sign In',
    'auth.signup': 'Create Account',
    'auth.staff_signin': 'Staff Sign In',
    'auth.fullname': 'Full Name',
    'auth.phone': 'Phone Number',
    'auth.google': 'Continue with Google',
    'auth.or': 'Or',
    'auth.no_account': "Don't have an account?",
    'auth.have_account': 'Already have an account?',
    'auth.hero_title': 'Your safe journey starts here',
    'auth.hero_subtitle': 'Join us to make your travel easier and more enjoyable.',
    'auth.stats_passengers': '5000+ passengers have traveled with us',
    'auth.register_success': 'Registration Successful! You can now login.',
    'auth.register_failed': 'Registration failed.',
    'auth.invalid_credentials': 'Invalid credentials.',
    'auth.error_occurred': 'An error occurred during login. Please try again.',
    'auth.default_credentials': 'Default Credentials',
    'auth.admin': 'Admin',
    'auth.counter': 'Counter',

    // About Us
    'about.title': 'About Us',
    'about.subtitle': 'Ticket Lagbe is a premium bus service in Bangladesh. We are committed to ensuring maximum comfort and safety for passengers.',
    'about.mission.title': 'Our Mission',
    'about.mission.desc': 'Our mission is to add a new dimension to the transport system of Bangladesh. We believe every passenger has the right to a safe and comfortable journey. Ticket Lagbe has been providing easy booking and advanced services through modern technology.',
    'about.why_choose.title': 'Why Choose Us?',
    'about.feature.safety': 'Maximum Safety',
    'about.feature.safety.desc': 'Every bus is controlled by GPS tracking and CCTV cameras.',
    'about.feature.staff': 'Expert Staff',
    'about.feature.staff.desc': 'Our drivers and helpers are highly skilled and passenger-friendly.',
    'about.feature.routes': 'Wide Routes',
    'about.feature.routes.desc': 'We provide regular services to major cities in Bangladesh.',

    // Refund Policy
    'refund.title': 'Refund Policy',
    'refund.subtitle': 'The rules regarding ticket cancellation and refund are given below. Please read before booking.',
    'refund.section1.title': '1. Ticket Cancellation Deadline',
    'refund.section1.item1': '80% refund will be given if the ticket is cancelled at least 12 hours before the scheduled departure.',
    'refund.section1.item2': '50% refund will be given if the ticket is cancelled 6-12 hours before departure.',
    'refund.section1.item3': 'No refund will be given if less than 6 hours are left before departure.',
    'refund.section1.item4': 'No refund is applicable for Eid advance tickets.',
    'refund.section2.title': '2. Refund Process',
    'refund.section2.item1': 'In case of online payment, refund will be returned to your original payment method (bKash/Nagad/Card) within 3-7 working days.',
    'refund.section2.item2': 'In case of tickets bought from the counter, refund must be taken by contacting the respective counter.',
    'refund.section2.item3': 'Service charges may apply for refund processing.',
    'refund.section3.title': '3. Special Circumstances',
    'refund.section3.desc': 'If Ticket Lagbe authorities cancel a trip for any reason, the passenger will receive a 100% refund or can change the ticket for a subsequent trip. No additional charges will be taken in this case.',
    'refund.section4.title': '4. Contact',
    'refund.section4.desc': 'For any refund related issues, call our helpline at 01900-000000 or email support@ticketlagbe.com.',

    // Terms & Conditions
    'terms.title': 'Terms & Conditions',
    'terms.subtitle': 'Please read the following terms carefully for using Ticket Lagbe. By booking a ticket, you agree to these terms.',
    'terms.section1.title': '1. Ticket Booking and Payment',
    'terms.section1.item1': 'Correct information (Name, Mobile Number, NID) must be provided during ticket booking.',
    'terms.section1.item2': 'Ticket will be confirmed after successful payment in case of online booking.',
    'terms.section1.item3': 'A confirmation SMS will be sent to the mobile phone after ticket booking.',
    'terms.section1.item4': 'Booking ID and NID must be shown while collecting tickets from the ticket counter.',
    'terms.section2.title': '2. Journey and Schedule',
    'terms.section2.item1': 'Passengers must be present at the counter at least 30 minutes before the scheduled time of the bus.',
    'terms.section2.item2': 'Bus time may change due to unavoidable reasons (e.g., traffic congestion, mechanical fault, natural disaster).',
    'terms.section2.item3': 'If the passenger is not present at the scheduled time, the ticket will be considered cancelled and no refund will be given.',
    'terms.section3.title': '3. Prohibited Items and Behavior',
    'terms.section3.item1': 'Smoking or carrying any kind of drugs inside the bus is strictly prohibited.',
    'terms.section3.item2': 'Carrying explosives, firearms or any illegal goods is a legally punishable offense.',
    'terms.section3.item3': 'The authorities reserve the right to drop a passenger from the bus if they behave rudely with fellow passengers.',
    'terms.section4.title': '4. Accountability',
    'terms.section4.desc': "Passengers' personal belongings must be kept at their own responsibility. The authorities will not be responsible if belongings are lost. However, if the journey is interrupted due to any mechanical fault, the authorities will arrange an alternative bus.",

    // HomePage
    'hero.title': 'Your Trusted Travel Partner',
    'hero.subtitle': 'Ticket Lagbe - Committed to ensuring comfortable and safe travel from one end of Bangladesh to the other.',
    'hero.btn.book': 'Book Ticket',
    'hero.btn.learn': 'Learn More',
    'stats.experience': 'Years Experience',
    'stats.buses': 'Modern Buses',
    'stats.drivers': 'Expert Drivers',
    'stats.passengers': 'Happy Passengers',
    'features.title': 'Why Choose Us?',
    'features.subtitle': 'We use modern technology and skilled manpower to ensure maximum comfort and safety for passengers.',
    'feature.safety.title': 'Maximum Safety',
    'feature.safety.desc': 'Every bus is equipped with GPS tracking and CCTV cameras.',
    'feature.comfort.title': 'Comfortable Seats',
    'feature.comfort.desc': 'Luxurious push-back seats and ample leg-space are ensured.',
    'feature.booking.title': 'Easy Booking',
    'feature.booking.desc': 'Book your preferred seat online in just a few minutes.',
    'routes.title': 'Popular Routes',
    'routes.subtitle': 'Regular services are available to major cities across the country.',
    'home.stats.routes': 'Number of Routes',
    'home.stats.safety': 'Safety Rating',
    'home.about.title': 'By your side with trust for over a decade',
    'home.about.desc1': 'Ticket Lagbe is a trusted name in the transport sector of Bangladesh. For over a decade, we have been providing top-notch service to passengers. Every journey begins with your safety and comfort in mind.',
    'home.about.desc2': 'Combining modern technology and skilled manpower, we have built a strong network that delivers you on time to every corner of the country.',
    'home.about.staff': 'Skilled Staff',
    'home.about.trips': 'Daily Trips',
    'home.feature.punctual.title': 'Punctual Journey',
    'home.feature.punctual.desc': 'We understand the value of time. Every trip starts and ends on schedule.',
    'home.routes.view_all': 'View All',
    'home.fare.info_title': 'Fare Information',
    'home.fare.title': 'Fare List & Station Selection',
    'home.fare.desc': 'Check the fare list according to your destination. We provide a premium travel experience at affordable prices.',
    'home.fare.not_found': 'No fare information found for this route.',
    'home.fare.try_other': 'Try selecting another route.',
    'home.cta.title': 'Start your journey today',
    'home.cta.desc': 'Download our mobile app or book tickets directly from the website.',
    'home.cta.btn': 'Start Booking',
    'home.helpline': 'Helpline',
    'home.route.from_price': 'from',
    'home.stats.passengers_val': '500k+',
    'home.stats.buses_val': '200+',
    'home.stats.routes_val': '50+',
    'home.stats.safety_val': '4.9/5',
    'home.stats.experience_val': '10+',
    'home.stats.staff_val': '500+',
    'home.stats.trips_val': '1000+',
    'home.fare.departure': 'Departure Station',
    'home.fare.arrival': 'Arrival Station',
    'home.fare.route': 'Route',
    'home.fare.to': 'to',
    'home.fare.non_ac': 'Non-AC Service',
    'home.fare.ac_standard': 'AC Standard',
    'home.fare.ac_premium': 'AC Premium',
    'home.fare.label': 'Fare',
    'city.dhaka': 'Dhaka',
    'city.chattogram': 'Chattogram',
    'city.sylhet': 'Sylhet',
    'city.rajshahi': 'Rajshahi',
    'city.coxsbazar': "Cox's Bazar",
    'city.khulna': 'Khulna',
    'city.rangpur': 'Rangpur',
    'city.cumilla': 'Cumilla',
    'city.feni': 'Feni',
    'city.brahmanbaria': 'Brahmanbaria',
    'city.habiganj': 'Habiganj',
    'city.tangail': 'Tangail',
    'city.sirajganj': 'Sirajganj',
    'city.bogra': 'Bogra',
    'city.gaibandha': 'Gaibandha',
    'booking.route.origin': 'Origin',
    'booking.route.destination': 'Destination',
    'booking.route.stops': 'Major Stops',
    'booking.route.duration': 'Travel Time',
    'booking.route.distance': 'Distance',
    'booking.bus.seats_left': 'Seats Left',
    'booking.bus.departure': 'Departure',
    'booking.bus.arrival': 'Arrival',
    'booking.payment.bKash': 'bKash',
    'booking.payment.nagad': 'Nagad',
    'booking.payment.card': 'Card',
    'booking.payment.pay_later': 'Book Without Payment',
    'booking.payment.redirecting': 'Redirecting to payment gateway...',
    'booking.confirmation.portal': 'Portal',
    'booking.confirmation.print_note': 'This is an electronic ticket. Please keep it with you during travel.',
    'my_bookings.total_paid': 'Total Paid',
    'booking.error.name_required': 'Name is required',
    'booking.error.name_length': 'Name must be at least 3 characters',
    'booking.error.phone_required': 'Phone number is required',
    'booking.error.phone_invalid': 'Invalid phone number (e.g., 017XXXXXXXX)',
    'booking.cancel_confirm': 'Are you sure you want to cancel this booking?',

    // BookingPortal
    'booking.search.title': 'Find Tickets',
    'booking.from': 'From',
    'booking.to': 'To',
    'booking.date': 'Journey Date',
    'booking.btn.search': 'Search Buses',
    'booking.results.title': 'Available Buses',
    'booking.seats.left': 'Seats Left',
    'booking.btn.view_seats': 'View Seats',
    'booking.seats.select': 'Select Seats',
    'booking.seats.selected': 'Selected Seats',
    'booking.total': 'Total Fare',
    'booking.btn.checkout': 'Proceed to Payment',
    'booking.passenger.info': 'Passenger Information',
    'booking.passenger.name': 'Name',
    'booking.passenger.phone': 'Phone Number',
    'booking.confirmation.title': 'Booking Successful!',
    'booking.confirmation.msg': 'Your ticket booking is complete. Please save the following information.',
    'booking.id': 'Booking ID',
    'booking.status': 'Status',
    'booking.my_bookings': 'My Bookings',

    // Admin/Counter
    'admin.title': 'Admin Panel',
    'admin.profile.edit': 'Edit Admin Profile',
    'admin.profile.name': 'Full Name',
    'admin.profile.email': 'Email Address',
    'admin.profile.save': 'Save Changes',
    'admin.counter.add': 'Add New Counter',
    'admin.counter.name': 'Counter Name',
    'admin.counter.location': 'Location',
    'admin.counter.phone': 'Phone Number',
    'admin.counter.save': 'Add Counter',
    'admin.bus.register': 'Register New Bus',
    'admin.bus.name': 'Bus Name',
    'admin.bus.reg_no': 'Registration No',
    'admin.bus.driver': 'Driver Name',
    'admin.bus.driver_phone': 'Driver Phone',
    'admin.bus.last_maintenance': 'Last Maintenance',
    'admin.bus.next_maintenance': 'Next Maintenance',
    'admin.bus.capacity': 'Capacity',
    'admin.bus.save': 'Register Bus',
    'admin.route.add': 'Add New Route',
    'admin.route.from': 'From City',
    'admin.route.to': 'To City',
    'admin.route.distance': 'Distance (km)',
    'admin.route.duration': 'Duration',
    'admin.route.fare': 'Fare (৳)',
    'admin.route.save': 'Add Route',
    'admin.user.add': 'Add New User',
    'admin.user.role': 'Role',
    'admin.user.password': 'Password',
    'admin.user.save': 'Create User',
    'admin.schedule.add': 'Add New Schedule',
    'admin.schedule.bus': 'Select Bus',
    'admin.schedule.route': 'Select Route',
    'admin.schedule.departure': 'Departure Time',
    'admin.schedule.arrival': 'Arrival Time',
    'admin.schedule.date': 'Date',
    'admin.schedule.save': 'Add Schedule',
    'admin.nav.dashboard': 'Dashboard',
    'admin.nav.buses': 'Buses',
    'admin.nav.counters': 'Counters',
    'admin.nav.users': 'Users',
    'admin.nav.routes': 'Routes',
    'admin.nav.schedules': 'Schedules',
    'admin.nav.bookings': 'Bookings',
    'admin.nav.reports': 'Report',
    'admin.nav.settings': 'Settings',
    'admin.nav.logout': 'Logout',
    'admin.search.placeholder': 'Search bookings...',
    'admin.notifications': 'Notifications',
    'admin.stats.totalRevenue': 'Total Revenue',
    'admin.stats.onlineSales': 'Online Sales',
    'admin.stats.offlineSales': 'Offline Sales',
    'admin.stats.ticketsSold': 'Tickets Sold',
    'admin.stats.todaySales': "Today's Sales",
    'admin.stats.totalPassengers': 'Total Passengers',
    'admin.stats.activeBuses': 'Active Buses',
    'admin.stats.pendingIssues': 'Pending Issues',
    'admin.bookings.recent': 'Recent Bookings',
    'admin.table.bookingId': 'Booking ID',
    'admin.table.passenger': 'Passenger',
    'admin.table.phoneId': 'Phone & ID',
    'admin.table.route': 'Route',
    'admin.table.time': 'Time',
    'admin.table.status': 'Status',
    'admin.table.amount': 'Amount',
    'admin.table.action': 'Action',
    'admin.table.busNameReg': 'Bus Name & Reg',
    'admin.table.driverDetails': 'Driver Details',
    'admin.table.maintenance': 'Maintenance',
    'admin.table.capacity': 'Capacity',
    'admin.table.last': 'Last',
    'admin.table.next': 'Next',
    'admin.dashboard.overview': 'Dashboard Overview',
    'admin.dashboard.welcome': 'Welcome to Ticket Lagbe Admin Panel.',
    'admin.dashboard.generateReport': 'Generate Report',
    'admin.dashboard.todaySummary': "Today's Booking Summary",
    'admin.dashboard.liveBusStatus': 'Live Bus Status',
    'admin.dashboard.quickActions': 'Quick Actions',
    'admin.dashboard.addBus': 'Add Bus',
    'admin.dashboard.newRoute': 'New Route',
    'admin.dashboard.addCounter': 'Add Counter',
    'admin.dashboard.bookTicket': 'Book Ticket',
    'admin.manage.buses.title': 'Bus Management',
    'admin.manage.buses.desc': 'Manage all buses in your fleet here.',
    'admin.portal': 'Portal',
    'admin.fleet.fleetEfficiency': 'Fleet Efficiency',
    'admin.table.busName': 'Bus Name',
    'admin.table.regNo': 'Reg No',
    'admin.table.lastService': 'Last Service',
    'admin.table.nextService': 'Next Service',
    'admin.table.fuelEfficiency': 'Fuel Efficiency',
    'admin.counter.counterPerformance': 'Counter Performance',
    'admin.table.counterName': 'Counter Name',
    'admin.table.target': 'Target',
    'admin.stats.direct_customer': 'Direct Customer',
    'admin.manage.counters.title': 'Counter Management',
    'admin.manage.counters.desc': 'Manage all your counters here.',
    'admin.table.phone': 'Phone',
    'admin.table.editDetails': 'Edit Details',
    'admin.table.routePath': 'Route Path',
    'admin.table.distanceDuration': 'Dist & Duration',
    'admin.table.standardRoute': 'Standard Route',
    'common.est': 'Est.',
    'admin.manage.schedules.title': 'Schedule Management',
    'admin.manage.schedules.desc': 'Manage bus schedules here.',
    'admin.table.dateTime': 'Date & Time',
    'admin.table.availability': 'Availability',
    'admin.manage.users.title': 'User Management',
    'admin.manage.users.desc': 'Manage system users.',
    'admin.manage.owner': 'Bus Owner',
    'admin.manage.owner.desc': 'Manage bus owner accounts and their buses.',
    'owner.nav.dashboard': 'Dashboard',
    'owner.nav.counters': 'Counters',
    'owner.nav.staff': 'Staff Management',
    'owner.nav.reports': 'Reports',
    'owner.stats.totalRevenue': 'Total Revenue',
    'owner.stats.totalTickets': 'Total Tickets',
    'owner.stats.activeBuses': 'Active Buses',
    'owner.stats.totalStaff': 'Total Staff',
    'owner.manage.counters.title': 'My Counters',
    'owner.manage.counters.desc': 'Manage counters assigned to your buses.',
    'owner.manage.staff.title': 'Staff Management',
    'owner.manage.staff.desc': 'Add or remove staff for your counters.',
    'owner.reports.title': 'My Bus Reports',
    'owner.reports.desc': 'View revenue and performance reports for your buses.',
    'admin.manage.users.initialize': 'Initialize User Profiles',
    'admin.table.user': 'User',
    'admin.table.email': 'Email',
    'admin.modal.counter.placeholder': 'Select Counter',
    'admin.stats.totalSales': 'Total Sales',
    'admin.stats.totalTickets': 'Total Tickets',
    'admin.stats.counterSales': 'Counter Sales',
    'common.report': 'Report',
    'common.viewDetails': 'View Details',
    'admin.table.routeTime': 'Route & Time',
    'admin.table.counterStaff': 'Counter & Staff',
    'common.travel': 'Travel',
    'common.at': 'at',
    'common.online': 'Online',
    'common.staff': 'Staff',
    'admin.booking.directWeb': 'Direct Website',
    'admin.reports.title': 'Report',
    'admin.reports.revenue.title': 'Revenue & Sales Report',
    'admin.reports.revenue.desc': 'Analyze detailed revenue and sales trends.',
    'common.generateReport': 'Generate Report',
    'admin.reports.efficiency.title': 'Bus & Fleet Efficiency',
    'admin.reports.efficiency.desc': 'Track bus performance and maintenance.',
    'admin.reports.counter.title': 'Counter Performance',
    'admin.reports.counter.desc': 'Compare sales targets across counters.',
    'admin.reports.sales.title': 'Staff Sales Report',
    'admin.reports.sales.desc': 'View individual sales performance of counter staff.',
    'admin.settings.title': 'System Settings',
    'admin.settings.general': 'General Settings',
    'admin.settings.maintenanceMode': 'Maintenance Mode',
    'admin.settings.maintenanceMode.desc': 'Put the entire system in maintenance mode.',
    'admin.settings.emailNotifications': 'Email Notifications',
    'admin.settings.emailNotifications.desc': 'Enable email alerts for important updates.',
    'admin.settings.initialization': 'Data Initialization',
    'admin.settings.initialization.desc': 'Setup initial system data.',
    'admin.settings.profile': 'Profile Settings',
    'admin.settings.editProfile': 'Edit Profile',
    'admin.manage.counterUsers.title': 'Counter User Management',
    'admin.manage.counterUsers.desc': 'Manage counter staff accounts.',
    'admin.table.userName': 'User Name',
    'admin.table.assignedCounter': 'Assigned Counter',
    'common.remove': 'Remove',
    'common.filter': 'Filter',
    'common.export': 'Export',
    'common.noAddress': 'No Address',
    'common.id': 'ID',
    'common.na': 'N/A',
    'common.showing': 'Showing',
    'common.today': 'Today',
    'common.viewAll': 'View All',
    'common.to': 'to',
    'common.of': 'of',
    'common.arriving': 'Arriving',
    'common.seats': 'Seats',
    'common.save': 'Save',
    'status.active': 'Active',
    'status.maintenance': 'Maintenance',
    'status.inactive': 'Inactive',
    'admin.table.id': 'Booking ID',
    'admin.table.counter': 'Counter',
    'admin.table.staff': 'Staff',
    'admin.table.actions': 'Actions',
    'admin.action.print': 'Print Ticket',
    'admin.action.cancel': 'Cancel Booking',
    'admin.action.view': 'View Details',
    'admin.action.edit': 'Edit',
    'admin.action.delete': 'Delete',
    'admin.action.save': 'Save',
    'admin.action.cancel_btn': 'Cancel',
    'admin.action.close': 'Close',
    'admin.report.generate': 'Generate Report',
    'admin.report.revenue': 'Revenue Report',
    'admin.report.efficiency': 'Bus Efficiency',
    'admin.report.performance': 'Counter Performance',
    'admin.report.staff_sales': 'Sales by Counter & Staff',
    'admin.report.summary': 'General Dashboard Summary',
    'admin.report.counter_summary': 'Summary by Counter',
    'admin.report.channel': 'Counter/Channel',
    'admin.report.metric': 'Metric',
    'admin.report.value': 'Value',
    'admin.report.change': 'Change',
    'admin.report.date_issued': 'Date Issued',
    'admin.report.issued_by': 'Issued By',
    'admin.report.title': 'Ticket Lagbe - Admin Portal',
    'admin.report.generated_on': 'Generated on:',
    'admin.report.type': 'Report Type:',

    // Admin Modals & Details
    'admin.modal.busDetails': 'Bus Details',
    'admin.modal.maintenanceHistory': 'Maintenance History',
    'admin.modal.driverInfo': 'Driver Information',
    'admin.modal.regNo': 'Registration No',
    'admin.modal.status': 'Status',
    'admin.modal.capacity': 'Capacity',
    'admin.modal.lastServiced': 'Last Serviced',
    'admin.modal.nextScheduled': 'Next Scheduled',
    'admin.modal.editBus': 'Edit Bus',
    'admin.modal.registerBus': 'Register New Bus',
    'admin.modal.busName': 'Bus Name',
    'admin.modal.driverName': 'Driver Name',
    'admin.modal.driverPhone': 'Driver Phone',
    'admin.modal.assignedRoute': 'Assigned Route',
    'admin.modal.capacitySeats': 'Bus Capacity (Seats)',
    'admin.modal.lastMaintenance': 'Last Maintenance',
    'admin.modal.nextMaintenance': 'Next Maintenance',
    'admin.modal.addRoute': 'Add New Route',
    'admin.modal.from': 'From',
    'admin.modal.to': 'To',
    'admin.modal.distance': 'Distance',
    'admin.modal.duration': 'Duration',
    'admin.modal.fareBdt': 'Fare (BDT)',
    'admin.modal.addSchedule': 'Add New Schedule',
    'admin.modal.selectBus': 'Select Bus',
    'admin.modal.selectRoute': 'Select Route',
    'admin.modal.date': 'Date',
    'admin.modal.seats': 'Seats',
    'admin.modal.departure': 'Departure',
    'admin.modal.arrival': 'Arrival',
    'admin.modal.addCounterUser': 'Add Counter User',
    'admin.modal.fullName': 'Full Name',
    'admin.modal.email': 'Email',
    'admin.modal.password': 'Password',
    'admin.modal.assignCounter': 'Assign Counter',
    'admin.modal.addNewUser': 'Add New User',
    'admin.modal.role': 'Role',
    'admin.modal.editProfile': 'Edit Admin Profile',
    'admin.modal.addCounter': 'Add New Counter',
    'admin.modal.counterName': 'Counter Name',
    'admin.modal.location': 'Location',
    'admin.modal.phone': 'Phone Number',

    // Counter Dashboard
    'counter.nav.dashboard': 'Dashboard',
    'counter.nav.sellTickets': 'Sell Tickets',
    'counter.nav.myBookings': 'My Bookings',
    'counter.portal.title': 'Counter Portal',
    'counter.portal': 'Portal',
    'counter.sell.subtitle': 'Sell tickets and collect passenger information',
    'counter.sell.searchPlaceholder': 'Search bus or route...',
    'counter.sell.bookNow': 'Book Now',
    'counter.bookings.subtitle': 'View all bookings made from your counter here',
    'counter.bookings.searchPlaceholder': 'Search by booking ID or name...',
    'counter.dashboard.dailySalesSummary': 'Daily Sales Summary',
    'counter.dashboard.overviewToday': 'Overview Today -',
    'counter.dashboard.totalCombined': 'Total Combined',
    'counter.dashboard.onlineMobile': 'Online & Mobile',
    'counter.dashboard.digitalPayments': 'Digital Payments',
    'counter.dashboard.offlineCash': 'Offline & Cash',
    'counter.dashboard.cashAtCounter': 'Cash at Counter',
    'counter.dashboard.salesByService': 'Sales by Service',
    'counter.dashboard.acServices': 'AC Services',
    'counter.dashboard.nonAcServices': 'Non-AC Services',
    'counter.dashboard.downloadReport': 'Download Report',
    'counter.dashboard.todaysSchedule': "Today's Schedule",
    'counter.dashboard.sellTicket': 'Sell Ticket',
    'counter.dashboard.vsYesterday': '+12.5% vs Yesterday',
    'counter.dashboard.acServicesStats': '৳{amount} ({count} {tickets})',
    'counter.dashboard.nonAcServicesStats': '৳{amount} ({count} {tickets})',
    'counter.ticket.printTitle': 'Print Ticket',
    'counter.ticket.id': 'Ticket ID',
    'counter.ticket.passenger': 'Passenger',
    'counter.ticket.phone': 'Phone',
    'counter.ticket.passengerId': 'Passenger ID',
    'counter.ticket.date': 'Date',
    'counter.ticket.seatWise': 'Seat-wise Passengers',
    'counter.ticket.address': 'Address',
    'counter.ticket.bus': 'Bus',
    'counter.ticket.route': 'Route',
    'counter.ticket.seats': 'Seats',
    'counter.ticket.totalPaid': 'Total Paid',
    'counter.ticket.printNow': 'Print Now',
    'counter.ticket.download': 'Download',
    'counter.ticket.close': 'Close',
    'counter.download.confirmTitle': 'Confirm Download Format',
    'counter.download.confirmMsg': 'Please choose your preferred format. The ticket contains a QR Code which is required for passenger verification at the time of boarding.',
    'counter.download.noticeTitle': 'Verification Notice',
    'counter.download.noticeMsg': 'The QR code must be clearly legible. We recommend the PDF format for the best printing quality and verification reliability.',
    'counter.download.image': 'Image',
    'counter.download.imageFormat': 'PNG Format',
    'counter.download.document': 'Document',
    'counter.download.documentFormat': 'PDF Format',
    'counter.notifications.title': 'Notifications',
    'counter.notifications.markAllRead': 'Mark all as read',
    'counter.notifications.empty': 'No new notifications',
    'counter.notifications.viewAll': 'View All',
    'counter.search.placeholder': 'Search...',
    'counter.alert.fill_details': 'Please fill all details and select at least one seat.',
    'counter.alert.seat_details': 'Please fill details for seat {seat}',
    'counter.alert.reserve_success': 'Booking reserved successfully! Valid until {time}',
    'counter.alert.confirm_success': 'Ticket confirmed successfully!',
    'counter.alert.cancel_confirm': 'Are you sure you want to cancel this booking?',
    'counter.alert.cancel_success': 'Ticket cancelled successfully!',
    'counter.alert.error': 'Error: {message}',
    'counter.alert.failed_sell': 'Failed to sell ticket. Please try again.',
    'counter.alert.failed_confirm': 'Failed to confirm ticket.',
    'counter.alert.failed_cancel': 'Failed to cancel ticket.',
    'counter.alert.failed_download': 'Failed to download. Please try again.',
    'counter.alert.failed_pdf': 'Failed to generate PDF.',
    'report.sales_report': 'Sales Report',
    'report.summary_stats': 'Summary Statistics',
    'report.metric': 'Metric',
    'report.value': 'Value',
    'report.detailed_bookings': 'Detailed Bookings',
    'counter.bookings.allStatus': 'All Status',
    'counter.bookings.allDates': 'All Dates',
    'counter.bookings.exportCsv': 'Export CSV',
    'admin.table.ticketId': 'Ticket ID',
    'admin.table.busRoute': 'Bus & Route',
    'admin.table.seats': 'Seats',
    'table.status.confirmed': 'Confirmed',
    'table.status.reserved': 'Reserved',
    'table.status.cancelled': 'Cancelled',
    'table.status.pending': 'Pending',
    'counter.bookings.noResults': 'No bookings found.',
    'counter.sell.modalTitle': 'Ticket Booking',
    'counter.sell.selectSeats': 'Select Seats',
    'common.total': 'Total',
    'counter.sell.passengerName': 'Passenger Name',
    'counter.sell.fullNamePlaceholder': 'Enter full name',
    'counter.sell.phoneNumber': 'Phone Number',
    'counter.sell.passengerId': 'Passenger ID (Optional)',
    'counter.sell.idPlaceholder': 'NID or Birth Reg',
    'counter.sell.address': 'Address',
    'counter.sell.addressPlaceholder': 'Current address',
    'counter.sell.individualDetails': 'Individual details for each seat',
    'common.seat': 'Seat',
    'counter.sell.bookingType': 'Booking Type',
    'common.purchase': 'Direct Purchase',
    'common.reserveNoMoney': 'Reservation (No Payment)',
    'counter.sell.reservationExpiry': 'Reservation Expiry (Mins)',
    'counter.sell.paymentMethod': 'Payment Method',
    'counter.sell.totalAmount': 'Total Amount',
    'counter.sell.confirmPrint': 'Confirm & Print',
    'counter.sell.reserveSeat': 'Reserve Seat',
    'common.tickets': 'Tickets',
    'counter.title': 'Counter',
    'common.coming_soon': 'Coming Soon',
    'common.name': 'Name',
    'common.phone': 'Phone',
    'admin.table.busInfo': 'Bus Info',
    'admin.table.departure': 'Departure',
    'admin.table.availableSeats': 'Available Seats',
    'admin.table.fare': 'Fare',

    // Common Dashboard
    'dashboard.header.notifications': 'Notifications',
    'dashboard.header.searchPlaceholder': 'Search ticket...',
    'dashboard.header.markAllRead': 'Mark all as read',
    'dashboard.header.noNotifications': 'No notifications yet',
    'dashboard.header.viewAllNotifications': 'View all notifications',
    'dashboard.header.backToHome': 'Back to Home',

    // Table & Actions
    'table.header.id': 'ID',
    'table.header.passenger': 'Passenger',
    'table.header.route': 'Route',
    'table.header.time': 'Time',
    'table.header.status': 'Status',
    'table.header.amount': 'Amount',
    'table.header.action': 'Action',
    'table.header.busInfo': 'Bus Info',
    'table.header.departure': 'Departure',
    'table.header.availableSeats': 'Available Seats',
    'table.action.edit': 'Edit',
    'table.action.delete': 'Delete',
    'table.action.view': 'View',
    'table.action.sellTicket': 'Sell Ticket',
    'table.action.bookNow': 'Book Now',

    // Status
    'status.confirmed': 'Confirmed',
    'status.cancelled': 'Cancelled',
    'status.reserved': 'Reserved',
    'status.onTime': 'On Time',
    'status.delayed': 'Delayed',

    // Buttons
    'button.saveChanges': 'Save Changes',
    'button.addCounter': 'Add Counter',
    'button.addUser': 'Add User',
    'button.registerBus': 'Register Bus',
    'button.addRoute': 'Add Route',
    'button.addSchedule': 'Add Schedule',
    'button.cancel': 'Cancel',
    'button.confirm': 'Confirm',
    'button.printTicket': 'Print Ticket',
    'button.downloadPDF': 'Download PDF',
    'button.viewAll': 'View All',
    'button.viewAllNotifications': 'View All Notifications',
    'button.backToHome': 'Back to Home',

    // UserProfile
    'profile.title': 'User Profile',
    'profile.edit': 'Edit Profile',
    'profile.logout': 'Logout',
    'profile.back': 'Back',
    'profile.member_since': 'Member Since:',
    'profile.total_trips': 'Total Trips',
    'profile.points': 'Points',
    'profile.saved_cards': 'Saved Cards',
    'profile.recent_activity': 'Recent Activity',
    'profile.view_all': 'View All',
    'profile.account_settings': 'Account Settings',
    'profile.security': 'Security',
    'profile.security_desc': 'Password & 2FA',
    'profile.notifications': 'Notifications',
    'profile.notifications_desc': 'Email & SMS alerts',
    'profile.payment_methods': 'Payment Methods',
    'profile.payment_methods_desc': 'Manage your cards',
    'profile.privacy': 'Privacy',
    'profile.privacy_desc': 'Data & visibility',
    'profile.membership_id': 'Membership ID:',
    'profile.expires': 'Expires:',
    'profile.card_holder': 'Card Holder',
    'profile.platinum': 'Platinum',
    'profile.premium_member': 'Premium Member',
    'profile.administrator': 'Administrator',
    'profile.counter_staff': 'Counter Staff',
    'profile.activity.booking': 'Booking',
    'profile.activity.payment': 'Payment',
    'profile.activity.support': 'Support',
    'profile.activity.confirmed': 'Confirmed',
    'profile.activity.success': 'Success',
    'profile.activity.resolved': 'Resolved',
    'profile.activity.hours_ago': 'hours ago',
    'profile.activity.yesterday': 'Yesterday',
    'profile.activity.days_ago': 'days ago',
    'profile.quick_stats': 'Quick Stats',
    'admin.manage.routes.title': 'Route List',
    'admin.manage.routes.desc': 'Manage all your routes here.',
    'admin.modal.addUser': 'Add New User',
    'admin.stats.target': 'Target',
    'admin.table.location': 'Location',
    'admin.table.role': 'Role',
    'booking.passenger.address': 'Address',
    'booking.route': 'Route',
    'common.available': 'Available',
    'common.booked': 'Booked',
    'common.cancel': 'Cancel',
    'common.confirm': 'Confirm',
    'common.confirm_delete': 'Are you sure you want to delete this item?',
    'common.confirmed': 'Confirmed',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.reserved': 'Reserved',
    'common.selected': 'Selected',
    'common.view': 'View',
    'counter.sell.offlineCash': 'Offline & Cash',
    'counter.sell.onlineMobile': 'Online & Mobile',
    'footer.copyright': 'Ticket Lagbe',
    'table.header.date': 'Date',
    'admin.alert.counter_success': 'Counter added successfully!',
    'admin.alert.counter_fail': 'Failed to add counter',
    'admin.alert.counter_user_success': 'Counter User profile created successfully!',
    'admin.alert.counter_user_fail': 'Failed to create counter user',
    'admin.alert.user_success': 'User created successfully!',
    'admin.alert.user_fail': 'Failed to create user',
    'admin.alert.bus_success': 'Bus registered successfully!',
    'admin.alert.bus_fail': 'Failed to register bus',
    'admin.alert.route_success': 'Route added successfully!',
    'admin.alert.route_fail': 'Failed to add route',
    'admin.alert.item_delete_success': 'Item deleted successfully!',
    'admin.alert.item_delete_fail': 'Failed to delete item',
    'admin.alert.user_update_success': 'User changes saved successfully!',
    'admin.alert.user_update_fail': 'Failed to save user changes',
    'admin.alert.bus_update_success': 'Bus details updated successfully!',
    'admin.alert.bus_update_fail': 'Failed to save bus changes',
    'admin.alert.counter_update_success': 'Counter details updated successfully!',
    'admin.alert.counter_update_fail': 'Failed to save counter changes',
    'admin.alert.route_update_success': 'Route details updated successfully!',
    'admin.alert.route_update_fail': 'Failed to save route changes',
    'admin.alert.schedule_success': 'Schedule added successfully!',
    'admin.alert.schedule_fail': 'Failed to add schedule',
    'admin.alert.schedule_update_success': 'Schedule updated successfully!',
    'admin.alert.schedule_update_fail': 'Failed to update schedule',
    'admin.alert.init_success': 'Default user profiles are already initialized in local state.',
    'admin.alert.report_fail': 'Failed to generate report. Please try again.',
    'admin.report.summary_title': 'General Dashboard Summary',
    'admin.report.revenue_title': 'Revenue Report',
    'admin.report.efficiency_title': 'Bus Efficiency',
    'admin.report.performance_title': 'Counter Performance',
    'admin.report.staff_sales_title': 'Sales by Counter & Staff',
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('en');

  const t = (key: string, params?: Record<string, string>): string => {
    let text = translations[language][key] || key;
    if (params) {
      Object.entries(params).forEach(([k, v]) => {
        text = text.replace(`{${k}}`, v);
      });
    }
    return text;
  };

  const formatNumber = (n: number | string): string => {
    if (n === undefined || n === null) return '';
    const numStr = n.toString();
    if (language === 'en') return numStr;
    const englishToBengali: Record<string, string> = {
      '0': '০', '1': '১', '2': '২', '3': '৩', '4': '৪',
      '5': '৫', '6': '৬', '7': '৭', '8': '৮', '9': '৯'
    };
    return numStr.split('').map(char => englishToBengali[char] || char).join('');
  };

  const formatCurrency = (n: number | string): string => {
    if (n === undefined || n === null) return '৳০';
    const num = typeof n === 'string' ? parseInt(n.replace(/[৳,]/g, '')) : n;
    if (isNaN(num)) return n.toString();
    const formatted = new Intl.NumberFormat('en-US').format(num);
    return `৳${formatNumber(formatted)}`;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, formatNumber, formatCurrency }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
